<?php

namespace Armd\ExtendedNewsBundle\Repository;

use Armd\Bundle\NewsBundle\Repository\NewsRepository as BaseRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends BaseRepository
{
}