<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Armd\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Datetime $last_activitylastActivity
     */
    private $lastActivity;

    /**
     * @var integer $okUid
     */
    protected $odnoklassnikiUid;

    /**
     * @var integer $vkUid
     */
    protected $vkontakteUid;


    /**
     * @var string $socialName
     */
    protected $socialName;

    /**
     * @var \Armd\AtlasBundle\Entity\Region
     */
    protected $region;

    /**
     * @var string $socialName
     */
    protected $biographyText;

    /**
     * @var string
     */
    protected $loginToken;

    /**
     * @var \DateTime
     */
    protected $loginTokenExpires;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $subscriptions;
    
    /**
     * @var integer
     */
    protected $noticeOnComment = 0;

    /**
     * @param \Doctrine\Common\Collections\Collection $subscriptions
     */
    public function setSubscriptions($subscriptions)
    {
        $this->subscriptions = $subscriptions;
    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get odnoklassnikiUid
     *
     * @return integer $odnoklassnikiUid
     */
    public function getOdnoklassnikiUid()
    {
        return $this->odnoklassnikiUid;
    }

    /**
     * Set odnoklassnikiUid
     *
     * @param integer $odnoklassnikiUid
     *
     * @return User
     */
    public function setOdnoklassnikiUid($odnoklassnikiUid)
    {
        $this->odnoklassnikiUid = $odnoklassnikiUid;

        return $this;
    }

    /**
     * Get vkontakteUid
     *
     * @return integer $vkUid
     */
    public function getVkontakteUid()
    {
        return $this->vkontakteUid;
    }

    /**
     * Set vkUid
     *
     * @param integer $vkUid
     *
     * @return User
     */
    public function setVkontakteUid($vkUid)
    {
        $this->vkontakteUid = $vkUid;

        return $this;
    }

    /**
     * Set lastActivity
     *
     * @param \Datetime $lastActivity
     * @return User
     */
    public function setLastActivity($lastActivity)
    {
        $this->lastActivity = $lastActivity;
        return $this;
    }

    /**
     * Get lastActivity
     *
     * @return \Datetime
     */
    public function getLastActivity()
    {
        return $this->lastActivity;
    }

    /**
     * Set socialName
     *
     * @param string $socialName
     * @return User
     */
    public function setSocialName($socialName)
    {
        $this->socialName = $socialName;
        return $this;
    }

    /**
     * Get socialName
     *
     * @return \Datetime
     */
    public function getSocialName()
    {
        return $this->socialName;
    }
    /**
     * @var string $middlename
     */
    private $middlename;

    /**
     * @var string $city
     */
    private $city;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    protected $groups;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent:: __construct();
        
        $this->groups = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Set middlename
     *
     * @param string $middlename
     * @return User
     */
    public function setMiddlename($middlename)
    {
        $this->middlename = $middlename;
    
        return $this;
    }

    /**
     * Get middlename
     *
     * @return string 
     */
    public function getMiddlename()
    {
        return $this->middlename;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return User
     */
    public function setCity($city)
    {
        $this->city = $city;
    
        return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
        return $this->city;
    }

    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    /**
     * @return \Armd\AtlasBundle\Entity\Region
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * @param \Armd\AtlasBundle\Entity\Region $region
     * @return \Armd\UserBundle\Entity\User
     */
    public function setRegion($region)
    {
        $this->region = $region;
        return $this;
    }

    /**
     * @return string
     */
    public function getBiographyText()
    {
        return $this->biographyText;
    }

    /**
     * @param string $biographyText
     * @return \Armd\UserBundle\Entity\User
     */
    public function setBiographyText($biographyText)
    {
        $this->biographyText = $biographyText;
        return $this;
    }

    public function getLoginToken()
    {
        return $this->loginToken;
    }

    public function setLoginToken($loginToken)
    {
        $this->loginToken = $loginToken;
    }

    /**
     * @return \DateTime
     */
    public function getLoginTokenExpires()
    {
        return $this->loginTokenExpires;
    }

    /**
     * @param \DateTime $loginTokenExpires
     */
    public function setLoginTokenExpires($loginTokenExpires)
    {
        $this->loginTokenExpires = $loginTokenExpires;
    }
    
    /**
     * @return integer
     */
    public function getNoticeOnComment()
    {
        return (int)$this->noticeOnComment;
    }
    
    /**
     * @param integer $noticeOnComment
     */
    public function setNoticeOnComment($noticeOnComment)
    {
        $this->noticeOnComment = (int)$noticeOnComment;
    }

}
