<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Armd\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Datetime $last_activitylastActivity
     */
    private $lastActivity;

    /**
     * @var integer $okUid
     */
    protected $okUid;

    /**
     * @var integer $vkUid
     */
    protected $vkUid;

    /**
     * @var integer $fbUid
     */
    protected $fbUid;

    /**
     * @var integer $twUid
     */
    protected $twUid;

    /**
     * @var string $socialName
     */
    protected $socialName;

    /**
     * @var \Armd\AtlasBundle\Entity\Region
     */
    protected $region;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get okUid
     *
     * @return integer $okUid
     */
    public function getOkUid()
    {
        return $this->okUid;
    }

    /**
     * Set okUid
     *
     * @param integer $okUid
     *
     * @return User
     */
    public function setOkUid($okUid)
    {
        $this->okUid = $okUid;

        return $this;
    }

    /**
     * Get vkUid
     *
     * @return integer $vkUid
     */
    public function getVkUid()
    {
        return $this->vkUid;
    }

    /**
     * Set vkUid
     *
     * @param integer $vkUid
     *
     * @return User
     */
    public function setVkUid($vkUid)
    {
        $this->vkUid = $vkUid;

        return $this;
    }

    /**
     * Get fbUid
     *
     * @return integer $fbUid
     */
    public function getFbUid()
    {
        return $this->fbUid;
    }

    /**
     * Set fbUid
     *
     * @param integer $fbUid
     *
     * @return User
     */
    public function setFbUid($fbUid)
    {
        $this->fbUid = $fbUid;

        return $this;
    }

    /**
     * Get twUid
     *
     * @return integer $twUid
     */
    public function getTwUid()
    {
        return $this->twUid;
    }

    /**
     * Set twUid
     *
     * @param integer $twUid
     *
     * @return User
     */
    public function setTwUid($twUid)
    {
        $this->twUid = $twUid;

        return $this;
    }

    /**
     * Set lastActivity
     *
     * @param \Datetime $lastActivity
     * @return User
     */
    public function setLastActivity($lastActivity)
    {
        $this->lastActivity = $lastActivity;
        return $this;
    }

    /**
     * Get lastActivity
     *
     * @return \Datetime
     */
    public function getLastActivity()
    {
        return $this->lastActivity;
    }

    /**
     * Set socialName
     *
     * @param string $socialName
     * @return User
     */
    public function setSocialName($socialName)
    {
        $this->socialName = $socialName;
        return $this;
    }

    /**
     * Get socialName
     *
     * @return \Datetime
     */
    public function getSocialName()
    {
        return $this->socialName;
    }
    /**
     * @var string $middlename
     */
    private $middlename;

    /**
     * @var string $city
     */
    private $city;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    protected $groups;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent:: __construct();
        
        $this->groups = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Set middlename
     *
     * @param string $middlename
     * @return User
     */
    public function setMiddlename($middlename)
    {
        $this->middlename = $middlename;
    
        return $this;
    }

    /**
     * Get middlename
     *
     * @return string 
     */
    public function getMiddlename()
    {
        return $this->middlename;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return User
     */
    public function setCity($city)
    {
        $this->city = $city;
    
        return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
        return $this->city;
    }

    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    /**
     * @return \Armd\AtlasBundle\Entity\Region
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * @param \Armd\AtlasBundle\Entity\Region $region
     * @return \Armd\UserBundle\Entity\User
     */
    public function setRegion($region)
    {
        $this->region = $region;
        return $this;
    }

}