parameters:
    armd_paper_archive.manager.news.entity:  Armd\PaperArchiveBundle\Entity\PaperArchive

services:
    armd_paper_archive.admin.paper_archive:
        class: Armd\PaperArchiveBundle\Admin\PaperArchive
        tags:
            - { name: sonata.admin, manager_type: orm, group: PaperArchive, label: PaperArchive }
        arguments: [null, Armd\PaperArchiveBundle\Entity\PaperArchive, SonataAdminBundle:CRUD, @service_container]

    armd_paper_archive.admin.paper_edition:
        class: Armd\PaperArchiveBundle\Admin\PaperEdition
        tags:
            - { name: sonata.admin, manager_type: orm, group: PaperArchive, label: PaperEdition }
        arguments: [null, Armd\PaperArchiveBundle\Entity\PaperEdition, SonataAdminBundle:CRUD, @service_container]

    armd_paper_archive.listener.paper_archive:
        class: Armd\PaperArchiveBundle\EventListener\PaperArchiveListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }
        arguments: [@service_container]

    armd_paper_archive.manager.paper_archive:
        class: Armd\PaperArchiveBundle\Manager\PaperArchiveManager
        arguments:  [@doctrine.orm.entity_manager, @service_container]