armd_main_homepage:
    pattern:  /
    defaults: { _controller: ArmdMainBundle:Main:index }

armd_main_banner:
    pattern:  /banner
    defaults: { _controller: ArmdMainBundle:Main:banner }

armd_main_museums:
    pattern:  /museums
    defaults: { _controller: ArmdMainBundle:Main:museums }

armd_main_about:
    pattern:  /about
    defaults: { _controller: ArmdMainBundle:Main:about }

armd_main_services:
    pattern:  /services
    defaults: { _controller: ArmdMainBundle:Main:services }

armd_main_brodino:
    pattern:  /borodino
    defaults: { _controller: ArmdMainBundle:Borodino:index }

armd_main_special:
    pattern:  /special
    defaults: { _controller: ArmdMainBundle:Special:index }

armd_main_specialnews:
    pattern:  /special/news
    defaults: { _controller: ArmdMainBundle:Special:news }

armd_main_specialabout:
    pattern:  /special/about
    defaults: { _controller: ArmdMainBundle:Special:about }

armd_main_specialchronicles:
    pattern:  /special/chronicles
    defaults: { _controller: ArmdMainBundle:Special:chronicles }

armd_main_specialservices:
    pattern:  /special/services
    defaults: { _controller: ArmdMainBundle:Special:services }	

armd_main_random_russia_images:
    pattern: /main/random-russia-images
    defaults: { _controller: ArmdMainBundle:Main:randomRussiaImages }
    options:
        expose: true
