armd_main_homepage:
    pattern:  /
    defaults: { _controller: ArmdMainBundle:Main:index }

armd_main_banner:
    pattern:  /banner
    defaults: { _controller: ArmdMainBundle:Main:banner }

armd_main_museums:
    pattern:  /museums
    defaults: { _controller: ArmdMainBundle:Main:museums }

armd_main_about:
    pattern:  /about
    defaults: { _controller: ArmdMainBundle:Main:about }

armd_main_services:
    pattern:  /services
    defaults: { _controller: ArmdMainBundle:Main:services }

armd_main_brodino:
    pattern:  /borodino
    defaults: { _controller: ArmdMainBundle:Borodino:index }

armd_main_random_russia_images:
    pattern: /main/random-russia-images
    defaults: { _controller: ArmdMainBundle:Main:randomRussiaImages }
    options:
        expose: true
