parameters:
    armd_news.admin.subject.class:  Armd\MainBundle\Admin\Subject
    armd_news.admin.subject.entity: Armd\MainBundle\Entity\Subject

services:

    armd_news.admin.subject:
        class: %armd_news.admin.subject.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directories, label: Subjects }
        arguments: [null, %armd_news.admin.subject.entity%, SonataAdminBundle:CRUD, @service_container]
