parameters:
    armd_news.admin.subject.class:  Armd\MainBundle\Admin\Subject
    armd_news.admin.subject.entity: Armd\MainBundle\Entity\Subject
    armd_news.admin.show_on_main.class:  Armd\MainBundle\Admin\ShowOnMain
    armd_news.admin.show_on_main.entity: Armd\MainBundle\Entity\ShowOnMain

services:

    armd_news.admin.subject:
        class: %armd_news.admin.subject.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directories, label: Subjects }
        arguments: [null, %armd_news.admin.subject.entity%, SonataAdminBundle:CRUD, @service_container]

    armd_main.listener.master_slave:
        class: Armd\MainBundle\EventListener\MasterSlaveListener
        arguments: [@database_connection]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    armd_main.ajax_proxy:
        class: Armd\MainBundle\Ajax\AjaxProxy

    armd_main.menu_builder:
        class: Armd\MainBundle\Menu\Builder
        arguments: [@knp_menu.factory, @doctrine.orm.entity_manager]

    armd_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: armd_main.menu_builder
        factory_method: createMainMenu
        arguments: [@request]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias {{ knp_menu_render('main') }}

    armd_main.menu_finder:
        class: Armd\MainBundle\Menu\MenuFinder
        
    armd_news.admin.show_on_main:
        class: %armd_news.admin.show_on_main.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: Show on main }
        arguments: [null, %armd_news.admin.show_on_main.entity%, SonataAdminBundle:CRUD, @service_container]
