parameters:
#    blog.example.class: Armd\BlogBundle\Example

services:
    armd_blog.admin.blog:
        class: Armd\BlogBundle\Admin\Blog
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: Blog }
        arguments: [null, Armd\BlogBundle\Entity\Blog, SonataAdminBundle:CRUD, @service_container]
