parameters:
#    armd_mk_resources.example.class: Armd\Bundle\MkResourcesBundle\Example

services:
#    armd_mk_resources.example:
#        class: %armd_mk_resources.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
