parameters:
    armd_cms.theme.mk:
            name: ArmdMkResourcesBundle
            title: Министерство Культуры
            layout:
                main:
                    default: false
                    title: Шаблон главной страницы2
                index:
                    default: false
                    title: Шаблон главной страницы
                other_c:
                    default: false
                    title: 1 колонкa по всей ширине
                other_lc:
                    default: false
                    title: 2 колонки, левая и центр
                other_cr:
                    default: false
                    title: 2 колонки, центр и правая
                other_lcr:
                    default: false
                    title: 3 колонки
                plug:
                    default: false  
                    title: Заглушка для внутренних страниц
                    
            module:
                ArmdTextBundle:
                    template: 
                        default:
                            title: Основной шаблон
                        static-html:
                            title: Шаблон для HTML 
                ArmdExtendedNewsBundle:
                    template:
                        default:
                            title: Основной шаблон
                        main:
                            title: Шаблон для главной страницы
                        other_right:
                            title: Шаблон для правой части внутрених страниц
                        index:
                            title: Шаблон для главной страницы2   
                        official_news:
                            title: Шаблон для страницы официальное   
                ArmdCmsMenuBundle:
                    template:
                        default:
                            title: Основной шаблон
                        news_menu:
                            title: Меню для новостей      
                        events_menu:
                            title: Меню для событий 
                        official_menu:
                            title: Меню для раздела официальное
                        default_main:
                            title: Меню на главной   
                ArmdCultureAreaBundle:
                    template:                    
                        default:
                            title: Основной шаблон
                ArmdEventBundle:
                    template:
                        default:
                            title: Основной шаблон
                ArmdCommonBundle:
                    template:
                        default:
                            title: Основной шаблон
                            
                ArmdCultureMapBundle:
                    template:
                        default:
                            title: Основной шаблон
                ArmdTvigleBundle:
                    template:
                        default:
                            title: Основной шаблон
                            
services:
    armd_cms.template.mk:
        class: %armd_cms.service_template.class%
        arguments: [%armd_cms.theme.mk%]
        tags:
            -  { name: armd_cms.theme }
