armd_main_homepage:
    pattern:  /
    defaults: { _controller: ArmdMainBundle:Main:homepage }

armd_main_opinion:
    pattern:  /opinion/
    defaults: { _controller: ArmdMainBundle:Main:opinion }

armd_main_banner:
    pattern:  /banner/
    defaults: { _controller: ArmdMainBundle:Main:banner }

armd_main_about:
    pattern:  /about/
    defaults: { _controller: ArmdMainBundle:Main:about }

armd_main_services:
    pattern:  /services/{id}
    defaults: { _controller: ArmdMainBundle:Main:services, id: null }
    requirements:
        id:  \d+

armd_main_museum_reserve:
    pattern:  /museums/museum_reserve/
    defaults: { _controller: ArmdMainBundle:Main:museumReserve }

armd_main_may9:
    pattern:  /may9/
    defaults: { _controller: ArmdMainBundle:Main:may9 }

armd_main_may9_films:
    pattern:  /may9/may9_films/
    defaults: { _controller: ArmdMainBundle:Main:may9_films }

armd_main_may9_day:
    pattern:  /may9/may9_day/
    defaults: { _controller: ArmdMainBundle:Main:may9_day }

armd_main_library:
    pattern:  /library/
    defaults: { _controller: ArmdMainBundle:Main:library }

armd_main_print:
    pattern:  /print/
    defaults: { _controller: ArmdMainBundle:Main:print }

armd_main_banners:
    pattern:  /banners/
    defaults: { _controller: ArmdMainBundle:Main:banners }

armd_main_project_brodino:
    pattern:  /borodino/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Borodino:index.html.twig }

armd_main_project_1150:
    pattern:  /1150/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:1150:index.html.twig }

armd_main_project_traditions:
    pattern:  /traditions/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Traditions:index.html.twig }

armd_main_project_events:
    pattern: /events/
    defaults: { _controller: ArmdMainBundle:Project:events }

armd_main_project_news:
    pattern: /project-news/
    defaults: { _controller: ArmdMainBundle:Project:news }

armd_main_online_translation:
    pattern:  /online-translation/
    defaults: { _controller: ArmdMainBundle:Main:onlineTranslation }

armd_main_latest_topics:
    pattern: /latest-topics
    defaults: { _controller: ArmdMainBundle:Main:latestTopics }
    options: { expose: true }

armd_main_communication_platform_request:
    pattern: /complatform-request
    defaults: { _controller: ArmdMainBundle:Main:communicationPlatformRequest }
    options: { expose: true }

armd_test:
    pattern: /main/test-cache
    defaults: { _controller: ArmdMainBundle:Test:testCache }

armd_main_background_banner:
    pattern: /background-banner
    defaults: { _controller: ArmdMainBundle:Main:backgroundBanner }

armd_main_login_links:
    pattern: /login-links/
    defaults: { _controller: ArmdMainBundle:Main:loginLinks }

armd_main_culture_polls:
    pattern: /culture-polls/
    defaults: { _controller: ArmdMainBundle:Main:peopleCulturePolls }

armd_main_intermuseum:
    pattern:  /intermuseum/
    defaults: { _controller: ArmdMainBundle:Main:intermuseum }    
    
