armd_main_special_homepage:
    pattern:  /
    defaults: { _controller: ArmdMainBundle:Special:index }

armd_main_special_chronicles:
    pattern:  /chronicles
    defaults: { _controller: ArmdMainBundle:Special:chronicles }

armd_main_special_press:
    pattern:  /press-centre
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: armd_main_special_homepage }

armd_main_special_services:
    pattern:  /services
    defaults: { _controller: ArmdMainBundle:Special:services }
    
armd_main_special_about:
    pattern:  /about
    defaults: { _controller: ArmdMainBundle:Special:about }    	

armd_main_special_russian_images:
    pattern: /russian-images
    defaults: { _controller: ArmdMainBundle:Main:randomRussiaImages }
    options:
        expose: true
