services:
    armd_media_helper.listener.media:
        class: Armd\MediaHelperBundle\EventListener\MediaListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
        arguments: [@sonata.media.pool]

    armd_media_helper.type.armd_media_file_type:
        class: Armd\MediaHelperBundle\Form\Type\MediaFileType
        tags:
            - { name: form.type, alias: armd_media_file_type }

    armd_media_helper.type.armd_dcx_media_file_type:
        class: Armd\MediaHelperBundle\Form\Type\DCXMediaFileType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: armd_dcx_media_file_type }

    # armd_media_helper.data_transformer.dcx_media_transformer:
    #     class: Armd\MediaHelperBundle\Form\DataTransformer\DcxMediaTransformer
    #     arguments: [@doctrine.orm.entity_manager]

    armd_media_helper.type.armd_media_video_type:
        class: Armd\MediaHelperBundle\Form\Type\MediaVideoType
        tags:
            - { name: form.type, alias: armd_media_video_type }

    armd_media_helper.twig_extension.media_helper:
        class: Armd\MediaHelperBundle\Twig\MediaHelperExtension
        arguments: [@sonata.media.pool]
        tags:
          - { name: twig.extension }

#    armd_media_helper.generator.original:
#        class: Armd\MediaHelperBundle\Generator\OriginalGenerator

    armd_media_helper.configuration_pool:
        class: Armd\MediaHelperBundle\Pool\ConfigurationPool

    armd_media_helper.media_helper:
        class: Armd\MediaHelperBundle\Helper\MediaHelper

    sonata.media.provider.culturetv:
        class: Armd\MediaHelperBundle\Provider\CultureTvProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
            - sonata.media.provider.culturetv
            - null
            - @sonata.media.cdn.server
            - null
            - null
            - @sonata.media.buzz.browser
        calls:
            - [ setTemplates, [ { helper_thumbnail: ArmdMediaHelperBundle:Provider:thumbnail_culturetv.html.twig, helper_view: ArmdMediaHelperBundle:Provider:view_culturetv.html.twig } ] ]
#            - [ setResizer, [%armd_media_helper.providers.culturetv.resizer%] ]

    sonata.media.provider.tvigle:
        class: Armd\MediaHelperBundle\Provider\TvigleProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
            - sonata.media.provider.tvigle
            - null
            - @sonata.media.cdn.server
            - null
            - null
            - @sonata.media.buzz.browser
            - null
        calls:
            - [ setTemplates, [ { helper_thumbnail: ArmdMediaHelperBundle:Provider:thumbnail_tvigle.html.twig, helper_view: ArmdMediaHelperBundle:Provider:view_tvigle.html.twig } ] ]

    sonata.media.provider.dcx:
        class: Armd\MediaHelperBundle\Provider\DcxProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
            - sonata.media.provider.dcx
            - null
            - @sonata.media.cdn.server
            - null
            - null
            - []
            - []
            - @sonata.media.adapter.image.gd
            - @dcx.client
        calls:
            - [ setTemplates, [ { helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_image.html.twig } ] ]

