services:
    armd_address.sonata_admin.country_district:
        class: Armd\AddressBundle\Admin\CountryDistrictAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directories, label: CountryDistrict, show_in_dashboard: true }
        arguments: [null, Armd\AddressBundle\Entity\CountryDistrict, SonataAdminBundle:CRUD]