parameters:
#    armd_address.example.class: Armd\AddressBundle\Example

services:
    armd_atlas.sonata_admin.city:
        class: Armd\AddressBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directories, label: City, show_in_dashboard: true }
        arguments: [null, Armd\AddressBundle\Entity\City, SonataAdminBundle:CRUD]
