parameters:

services:
    armd_culture_area.admin.culture_area:
        class: Armd\CultureAreaBundle\Admin\CultureAreaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Culture Areas }
        arguments: [null, Armd\CultureAreaBundle\Entity\CultureArea, SonataAdminBundle:CRUD]