parameters:
    armd_culture_area.usagetypes:
        types:
            index:
                controller: culturearea
                action: index
                title: index
        group:
            index:
                types: [index]

services:
    armd_culture_area.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_area", %armd_culture_area.usagetypes%, "ArmdCultureAreaBundle"]
        tags:
            -  { name: armd_cms.usage }
