parameters:
    armd_culture_area.usagetypes:
        types:
            item:
                controller: CultureArea
                action: item
                route:
                    pattern: /{id}
                    requirements:
                        id: \d+
            list:
                controller: CultureArea
                action: list
            main:
                controller: CultureArea
                action: main
        group:
            list:
                types: [list]
            item:
                types: [item]
            main:
                types: [main]

services:
    armd_culture_area.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_area", %armd_culture_area.usagetypes%, "ArmdCultureAreaBundle"]
        tags:
            -  { name: armd_cms.usage }
