parameters:
    armd_culture_area.usagetypes:
        types:
            item:
                controller: CultureArea
                action: item
                title: Карточка
                route:
                    pattern: /{id}
                    requirements:
                        id: \d+
                params:
                    template:
                        title: Шаблон карточки
                        default: item
                        type: tempalte
                        bundleName: ArmdCultureAreaBundle
                        controller: CultureArea
                        action: item
            list:
                controller: CultureArea
                action: list
                title: Список
                params:
                    template:
                        title: Шаблон списка
                        default: list
                        type: tempalte
                        bundleName: ArmdCultureAreaBundle
                        controller: CultureArea
                        action: list
        group:
            item:
                types: [item]            
            list:
                types: [list]

services:
    armd_culture_area.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_area", %armd_culture_area.usagetypes%]
        tags:
            -  { name: armd_cms.usage }