parameters:
    armd_culture_area.usagetypes:
        types:
            item:
                controller: CultureArea
                action: item
                title: Карточка
                route:
                    pattern: /{id}
                    requirements:
                        id: \d+
            list:
                controller: CultureArea
                action: list
                title: Список
        group:
            item:
                types: [item]            
            list:
                types: [list]

services:
    armd_culture_area.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_area", %armd_culture_area.usagetypes%, "ArmdCultureAreaBundle"]
        tags:
            -  { name: armd_cms.usage }