_loginza_redirect_user:
    pattern:  /hello
    defaults: { _controller: Zim32LoginzaBundle:Default:index }

_loginza_login_user:
    pattern:  /loginza
    defaults: { _controller: Zim32LoginzaBundle:Default:login }

_loginza_social_reg:
    pattern:  /social
    defaults: { _controller: Zim32LoginzaBundle:Default:socialRegister }

_loginza_social_save:
    pattern:  /socialsave
    defaults: { _controller: Zim32LoginzaBundle:Default:socialSave }