parameters:

services:
    armd_news.admin.news:
        class: Armd\ExtendedNewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: News }
        arguments: [null, Armd\ExtendedNewsBundle\Entity\News, SonataAdminBundle:CRUD, @service_container]