imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: @ArmdCmsBundle/Resources/config/routing.xml }
    - { resource: @ArmdCmsBundle/Resources/config/parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

sonata_user:
    security_acl: true

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug%
    globals:
        ymaps_api_keys: "AFWDbE8BAAAA6EbIVAIAyR0FSeXkIt6YefBYNpGmv5CD75sAAAAAAAAAAABZ8ahRt4lUv480EGX1JSZGmnFb4A==~AIaDbE8BAAAAXU2KXAQAyQWFMrTgmHE5LRzjKY4LaHMJZh0AAAAAAAAAAAD4IAOY3YptF_w2WRJNfBlDUdk46A==~AJyJeU8BAAAAq8MjEAQAlsDIhR8bp6JW_9jqsw0mjCWFWhUAAAAAAAAAAADHuk5DtFdvoUI2ysCTLtDBLnsPZQ=="
    form:
        resources:
            - "ArmdAdminBundle:Form:fields.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

sonata_admin:
    security:
        handler: sonata.admin.security.handler.noop
    title: " "
    title_logo: /bundles/armdadmin/images/mincom-logo.png
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            tree: true
            timestampable: true

armd_cms:
    ignore_route_patterns:
        - /(.*)admin(.*)/
        - /(.*)sonata_user_impersonating(.*)/
        - /_profiler/
        - /_wdt/
        - /_configurator/
        - /_sys_(.*?)/
    template:
        theme: ArmdMkResourcesBundle


#simple_things_entity_audit:
#    audited_entities:
#        - ArmdCmsBundle\Entity\Page

sonata_media:
    db_driver: doctrine_orm
    default_context: default
    contexts:
        default:
            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
                 - sonata.media.provider.image
#                - sonata.media.provider.file
            formats:
                small: { width: 95,  quality: 95 }
                big:   { width: 266, height: 196, quality: 95 } 
                main:  { width: 488, height: 176, quality: 95 }
#               tiny:  { width: 95,  height: 95, quality: 95}
#        news:
#            providers:
#                - sonata.media.provider.vimeo
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#            formats:
#                small: { width: 150 , quality: 95 }
#                big:   { width: 500 , quality: 90 }
#        mincult:
#            providers:
#                - sonata.media.provider.image
#            formats:
#                small: { width: 150 , quality: 95 }
#                big:   { width: 800 , quality: 95 }

#    providers:
#        image:
#            resizer:    sonata.media.resizer.square

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
armd_tvigle:
    video_directory:  %kernel.root_dir%/../web/uploads/video
    video_url:  /uploads/video/%%
 

