imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:
        enabled: true
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        name: CULTURE_SESSID
#        domain:      %domain%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        progorod_api_key: %progorod_api_key%
    form:
        resources:
             - 'ArmdMediaHelperBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ "FOSCommentBundle", "ArmdCommunicationPlatformBundle" ]
    #bundles: [ "FOSCommentBundle", "ArmdCommentBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        toint: Armd\DoctrineBundle\DQL\PgSql\PgSqlToInt

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }
    
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            tree: true
            timestampable: true

sonata_admin:
    security:
        handler: sonata.admin.security.handler.noop
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
    templates:
        layout:  :Backend:base.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_user:
    security_acl: true
    class:
        user:   Armd\UserBundle\Entity\User
        group:  Armd\UserBundle\Entity\Group
    impersonating_route:    armd_news_list_index
    profile:
        form:
            type: armd_user_profile

    
sonata_media:
    default_context: news
    db_driver: doctrine_orm # or doctrine_mongodb
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.culturetv

            formats:
                adminPreview: { width: 314, height: 187, quality: 90}

        stuff:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.file
                - sonata.media.provider.culturetv
                - sonata.media.provider.youtube
            formats:
                original: { }

        news:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.culturetv
                - sonata.media.provider.youtube

            formats:
                adminPreview: { width: 314 , height: 187, quality: 90}
                billboard: { width: 761, height: 507 }
                eventsBillboard: { width: 358, height: 319 }
                latest: { width: 85, height: 65 }
                list: { width: 160, height: 107 }
                big: { width: 920 }
                thumbnail: { width: 85, height: 85 }
                searchAllResult: { width: 160, height: 107 }

        chronicle:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                adminPreview: { width: 314, height: 187, quality: 90}
                list: { width: 592 }

        atlas:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                image3d: { width: 405 }
                big: { width: 920 }
                thumbnail: { width: 85, height: 85 }
                imagesOfRussia: { width: 242, height: 187 }
                imagesOfRussiaSmall: { width: 85, height: 61 }
                imagesOfRussiaUnderMap: { width: 127, height: 107 }
                searchAllResult: { width: 160, height: 107 }
                sideBanner: { width: 308 }
                atlasW613: { width: 613 }
                atlasW63H56: { width: 63, height: 56 }

        atlas_icon:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                default: {width: 27, height: 45}


        lecture:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.file
                - sonata.media.provider.image
                - sonata.media.provider.culturetv
                - sonata.media.provider.youtube
            formats:
                xbig: { width: 670, height: 378 }
                big: { width: 335, height: 189 }
                tile: {width: 295, height: 228 }
                medium: { width: 111 }
                small: { width: 85 }
                searchAllResult: { width: 160, height: 107 }
                lectureW160H120: { width: 160, height: 120 }
                lectureH228: { height: 228 }

        museum:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http        
            providers:
                - sonata.media.provider.image
            formats:
                billboard: { width: 213 }
                searchAllResult: { width: 160, height: 107 }
                banner: { width: 922 }
                realSmall: { width: 285 }

        museum_guide:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                preview: { width: 105 }

        gallery:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                big: { width: 920 }
                thumbnail: { width: 85, height: 85 }
                archive: {width: 98}

        paper_archive:
            download:

                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                big: { width: 200 }
                small: { width: 97 }
        
        online_broadcast:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                default: { width: 278 }
                broadcastW600: { width: 600 }
                
        exhibit:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                default: { width: 600 }
                smallThumbnail: { width: 40 }
                smallZoom: { width: 127 }
                small: { width: 200 }
                
        lesson:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http        
            providers:
                - sonata.media.provider.image
            formats:
                searchAllResult: { width: 160, height: 107 }
                big: { width: 370 }
                small: { width: 125, height: 138 }        

        theater:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                item: { width: 600 }
                thumbnail: { width: 306, height: 179 }
                
        perfomance:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.file
                - sonata.media.provider.image
                - sonata.media.provider.culturetv
                - sonata.media.provider.youtube
            formats:
                xxbig: { width: 1200, height: 900 }
                xbig: { width: 670, height: 378 }
                big: { width: 335, height: 189 }
                tile: {width: 295, height: 228 }
                medium: { width: 111 }
                small: { width: 85 }
                searchAllResult: { width: 160, height: 107 }
                perfomanceW160H120: { width: 160, height: 120 }
                perfomanceH228: { height: 228 }
                
        person:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                big: { width: 600 }
                small: { width: 200 }

        banner:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                item: { height: 120 }

    cdn:
        server:
            path: %sonata_media_cdn%

    filesystem:
        local:
            directory:  %sonata_media_filesystem_path%
            create:     true

#    class:
#        media: "Armd\\Bundle\\MediaBundle\\Entity\\Media"
#        gallery: "Armd\\Bundle\\MediaBundle\\Entity\\Gallery"
#        gallery_has_media: "Armd\\Bundle\\MediaBundle\\Entity\\GalleryHasMedia"

    providers:
        file:
            resizer:    false
            filesystem: sonata.media.filesystem.local
            thumbnail:  sonata.media.thumbnail.format
            # Default set of allowed types doesn't include mp3.
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'mp3']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain', 'application/excel', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.ms-powerpoint', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.graphics', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.chart', 'application/vnd.oasis.opendocument.formula', 'application/vnd.oasis.opendocument.database', 'application/vnd.oasis.opendocument.image', 'text/comma-separated-values', 'text/xml', 'application/xml', 'application/zip', 'audio/mpeg']

        image:
            resizer:    sonata.media.resizer.simple #sonata.media.resizer.square
            filesystem: sonata.media.filesystem.local
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format

        youtube: ~

        dailymotion: ~



fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Armd\UserBundle\Entity\User

    group:
        group_class: Armd\UserBundle\Entity\Group
        
    registration:
        form:
            type:   armd_user_registration        

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Armd\MkCommentBundle\Entity\Comment
            thread: Armd\MkCommentBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl

    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

#            vote: Armd\CommentBundle\Entity\Vote
#    acl: true
#    service:
#        manager:
#            thread: fos_comment.manager.thread.acl
#            comment: fos_comment.manager.comment.acl
#            vote: fos_comment.manager.vote.acl

fos_rest:
    view:
        view_response_listener: force

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

knp_paginator:
    template: 
        pagination: ":Frontend:pagination.html.twig"

knp_menu:
    twig:
        template: :Frontend:menu.html.twig

armd_tvigle_video:
    api_service_url: http://pub.tvigle.ru/soap/index.php?wsdl
    api_login: Stella_l
    api_password: armada

armd_external_search:
    yandex_search_id: 2039240

armd_sphinx_search:
    indexes:
        All:
            %sphinxsearch_index_all%: ~
        Lectures:
            %sphinxsearch_index_lectures%: ~
        Atlas:
            %sphinxsearch_index_atlas%: ~
        Museums:
            %sphinxsearch_index_museums%: ~
        News:
            %sphinxsearch_index_news%: ~
        Lessons:
            %sphinxsearch_index_lessons%: ~            
        Theaters:
            %sphinxsearch_index_theaters%: ~
        Perfomances:
            %sphinxsearch_index_perfomances%: ~            

    searchd:
        host:   %sphinxsearch_host%
        port:   %sphinxsearch_port%
    indexer:
        bin:    %sphinxsearch_indexer_bin%

fos_oauth_server:
    db_driver: orm
    client_class:        Armd\OAuthBundle\Entity\Client
    access_token_class:  Armd\OAuthBundle\Entity\AccessToken
    refresh_token_class: Armd\OAuthBundle\Entity\RefreshToken
    auth_code_class:     Armd\OAuthBundle\Entity\AuthCode

    service:
        user_provider: fos_user.user_manager

jms_i18n_routing:
    default_locale: %locale%
    locales: [ru, en, fr]
    strategy: prefix_except_default

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

armd_media_helper:
    providers:
        culturetv:
            filesystem: sonata.media.filesystem.local
            resizer: sonata.media.resizer.simple
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.format

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: "tinymce"
    language: %locale%
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"

fpn_tag:
    model:
        tag_class:     Armd\TagBundle\Entity\Tag
        tagging_class: Armd\TagBundle\Entity\Tagging

parameters:
    sonata.user.admin.user.class: Armd\UserBundle\Admin\Entity\UserAdmin

armd_sitemap:
    host: culture.ru
    default_locale: ru
    locales: [ru, en]
    directory: sitemap # relative to server document_root (web)
    urls_per_file: 10000
