parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     mk
    database_user:     mk
    database_password: Fa3Sheer

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt
