parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     mk
    database_user:     mk
    database_password: Fa3Sheer

    mailer_transport:  gmail
    mailer_host:       localhost
    mailer_user:       randolik
    mailer_password:   annismylove

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt

    progorod_api_key:  e316fab34585f12b5506493c1c17d41c

    sphinxsearch_indexer_bin: c:/sphinx/bin/indexer.exe
    sphinxsearch_host: localhost
    sphinxsearch_port: 9312
    sphinxsearch_index_all: mk_all
    sphinxsearch_index_lectures: mk_lectures
    sphinxsearch_index_atlas: mk_atlas
    domain: 