parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     mk_my
    database_user:     postgres
    database_password: qazwsx12

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt

    progorod_api_key:  e316fab34585f12b5506493c1c17d41c

    tvigle:
        api_service_url:        http://pub.tvigle.ru/soap/index.php?wsdl
        api_login:       Stella_l
        api_password:    armada
