parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     mk
    database_user:     mk
    database_password: Fa3Sheer

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt

    progorod_api_key:  e316fab34585f12b5506493c1c17d41c

    loginza_secret_key: 17322cc0e68e0c86d67ee00c413d43bc
    loginza_widget_id: 27475

    sphinxsearch_indexer_bin: c:/sphinx/bin/indexer.exe
    sphinxsearch_host: localhost
    sphinxsearch_port: 9312
    sphinxsearch_index_all: mk_all
    sphinxsearch_index_lectures: mk_lectures
