parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     ~
    database_name:     mk
    database_user:     cmf-sandbox
    database_password: cmf-sandbox

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt
