blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

damedia_special_project:
    resource: "@DamediaSpecialProjectBundle/Resources/config/routing.yml"
    prefix:   /

armd_markup:
    resource: "@ArmdMarkupBundle/Controller/"
    type:     annotation
    prefix:   /markup

armd_exhibit:
    resource: "@ArmdExhibitBundle/Controller/"
    type:     annotation
    prefix:   /exhibit

armd_paper_archive:
    resource: "@ArmdPaperArchiveBundle/Controller/"
    type:     annotation
    prefix:   /

armd_museums:
    resource: "@ArmdMuseumBundle/Controller/"
    type:     annotation
    prefix:   /museums


armd_mk_comment:
    resource: "@ArmdMkCommentBundle/Controller/"
    type:     annotation
    prefix:   /

armd_main:
    resource: "@ArmdMainBundle/Resources/config/routing.yml"
    prefix:   /

armd_main_project_tolstoy:
    pattern:  /tolstoy/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Tolstoy:index.html.twig }
armd_main_project_romanovs:
    pattern:  /romanovs/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Romanovs:index.html.twig }
armd_main_project_mayakovsky:
    pattern:  /mayakovsky/
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Mayakovsky:index.html.twig }
armd_main_project_mayakovsky_tour:
    pattern:  /mayakovsky_tour
    defaults: { _controller: ArmdMainBundle:Project:index, template: ArmdMainBundle:Mayakovsky:tour.html.twig }    
armd_util:
    resource: "@ArmdUtilBundle/Controller/"
    type:     annotation
    prefix:   /

index:
    pattern: /main
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: armd_main_homepage
        permanent: true    

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media    


armd_user_admin:
    resource: '@ArmdUserBundle/Resources/config/routing/routing.yml'
    prefix:   /admin

fos_user_routing:
    resource: '@ArmdUserBundle/Resources/config/routing/fos_user_routing.yml'
    prefix:   /

armd_user_routing:
    resource: '@ArmdUserBundle/Resources/config/routing/armd_user_routing.yml'
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_comment_api:
   type: rest
   resource: "@FOSCommentBundle/Resources/config/routing.yml"
   prefix: /comment/api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
   
armd_main:
    resource: "@ArmdMainBundle/Resources/config/routing/routing.yml"
    prefix:   /
    
armd_main_special:
    resource: "@ArmdMainBundle/Resources/config/routing/special.yml"
    prefix:   /special   
   
armd_news:
    resource: "@ArmdNewsBundle/Controller/NewsController.php"
    type: annotation
    prefix: /press-centre

armd_news_admin:
    resource: "@ArmdNewsBundle/Controller/AdminController.php"
    type: annotation
    prefix: /admin/news

armd_chronicle:
    resource: '@ArmdChronicleBundle/Resources/config/routing.yml'
    prefix:   /chronicle

armd_banner:
    resource: "@ArmdBannerBundle/Controller/BannerController.php"
    type: annotation
    prefix: /banner

armd_atlas_bundle:
    resource: "@ArmdAtlasBundle/Controller/"
    type:     annotation
    prefix:   /atlas

armd_atlas_api:
    resource: "@ArmdAtlasBundle/Controller/Api"
    type:     annotation
    prefix:   /atlas/api

armd_search_bundle:
    resource: "@ArmdSearchBundle/Controller/"
    type:     annotation
    prefix:   /search/

armd_tvigle_video:
    resource: "@ArmdTvigleVideoBundle/Controller/"
    type: annotation
    prefix:   /tvigle_video

armd_media_helper:
    resource: "@ArmdMediaHelperBundle/Controller/"
    type:     annotation
    prefix:   /

armd_lecture:
    resource: "@ArmdLectureBundle/Controller/"
    type:     annotation
    prefix:   /
    
armd_perfomance:
    resource: "@ArmdPerfomanceBundle/Controller/"
    type:     annotation
    prefix:   /perfomance    
    
armd_user_bundle:
    resource: "@ArmdUserBundle/Controller/AuthenticationController.php"
    type: annotation
    prefix: /user
    
armd_social_auth:
    resource: "@ArmdSocialAuthBundle/Controller/"
    type:     annotation
    prefix:   /social-auth

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

armd_oauth:
    resource: "@ArmdOAuthBundle/Controller/"
    type:     annotation
    prefix:   /oauth

armd_online_translation:
    resource: '@ArmdOnlineTranslationBundle/Resources/config/routing.yml'
    prefix:   /broadcasts

armd_tag:
    resource: "@ArmdTagBundle/Controller/"
    type: annotation
    prefix: tag

armd_poll:
    resource: "@ArmdPollBundle/Controller/"
    type: annotation
    prefix: poll

armd_poll_archive:
    resource: "@ArmdMainBundle/Controller/PollArchiveController.php"
    type: annotation
    prefix: /
    
armd_show_on_main:
    resource: "@ArmdMainBundle/Controller/ShowOnMainController.php"
    type: annotation
    prefix: /show-on-main

armd_theater:
    resource: "@ArmdTheaterBundle/Controller/"
    type:     annotation
    prefix:   /theater

armd_external_search:
    resource: '@ArmdExternalSearchBundle/Controller/'
    type:     annotation
    prefix:   /external

armd_tourist_route_bundle:
    resource: "@ArmdTouristRouteBundle/Controller/"
    type:     annotation
    prefix:   /routes
