admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
        
ArmdUserBundle: 
    resource: '@ArmdUserBundle/Resources/config/routing/security.xml'
    prefix:   /admin    

ArmdAdminBundle:  
    resource: "@ArmdAdminBundle/Resources/config/routing/routing.yml"  
    prefix:   /_sys/admin

pages:
    resource: ArmdCmsBundle:Page
    type: db

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
