admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

ApplicationSonataUserBundle:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/security.xml'
    prefix:   /admin

ArmdCommunicationPlatformBundle_proposals:
    resource: "@ArmdCommunicationPlatformBundle/Resources/config/routing/proposals.yml"
    prefix:   /cp
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
