ArmdCultureMapBundle:
    resource: "@ArmdCultureMapBundle/Resources/config/routing.yml"
    prefix:   /_sys/map

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

ApplicationSonataUserBundle:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/application_admin_security.xml'
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
pages:
    resource: ArmdCmsBundle:Page
    type: db    