ArmdAtlasBundle:
    resource: "@ArmdAtlasBundle/Controller/"
    type:     annotation
    prefix:   /atlas
#ArmdMainBundle:
#    resource: "@ArmdMainBundle/Resources/config/routing.yml"
#    prefix:   /

index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: armd_news_list_index
        permanent: true    

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media    

ApplicationSonataUserBundle:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/routing.yml'
    prefix:   /admin

fos_user_routing:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/fos_user_routing.yml'
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

zim32_loginza:
    resource: '@Zim32LoginzaBundle/Resources/config/routing.yml'
    prefix:   /

ArmdCommunicationPlatformBundle_proposals:
    resource: "@ArmdCommunicationPlatformBundle/Resources/config/routing/proposals.yml"
    prefix:   /cp

fos_comment_api:
   type: rest
   resource: "@FOSCommentBundle/Resources/config/routing.yml"
   prefix: /comment/api
   
armd_news:
    resource: "@ArmdNewsBundle/Controller/NewsController.php"
    type: annotation
    prefix: /press-centre

armd_banner:
    resource: "@ArmdBannerBundle/Controller/BannerController.php"
    type: annotation
    prefix: /banner

    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
