ArmdCommunicationPlatformBundle_proposals:
    resource: "@ArmdCommunicationPlatformBundle/Resources/config/routing/proposals.yml"
    prefix:   /cp

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
