jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
        
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
            
    firewalls:
        admin:
            pattern:            /admin/
            anonymous:          ~            
            context:            user
            switch_user:        true
            form_login:
                login_path:             /admin/login
                check_path:             /admin/login_check
                default_target_path:    /admin/dashboard                
                provider:               fos_userbundle                
                use_forward:            false                
                failure_path:           null
                use_referer:            true
            logout:
                path:           /admin/logout
                target:         /admin/login
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        # URL of FOSUserBundle which need to be available to anonymous users
        #- { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end
        
        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
