jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EXPERT, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EXPERT:      [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # -> custom firewall for the admin area of the URL
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                login_path:             /admin/login
                check_path:             /admin/login_check
                default_target_path:    /admin/dashboard
                provider:               fos_userbundle
                use_forward:            false
                failure_path:           null
                use_referer:            true
            logout:
                path:           /admin/logout
                target:         /admin/login

            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 360000
                domain:   ~ # Defaults to the current domain from $_SERVER
        # -> end custom configuration

        # defaut login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    true
                check_path:     /login_check
#                default_target_path: armd_news_list_index
                failure_path:   null
                use_referer:    true
                success_handler: armd_user.security.authentication_success_handler
            logout:
                path:           /logout
                target:         armd_news_list_index
                success_handler: armd_user.security.logout_success_handler
            anonymous:          true

            armd_social_auth:
                auth_provider_parameters:

                    default:

                    roskult.ru:
                        vkontakte:
                            app_id: 3118810
                            secret: yTocvcEwl4cv4NHNJJEl
                        facebook:
                            app_id: 182778148514104
                            secret: 19c7d10f46b7e753c81143c27d48357c
                        twitter:
                            oauth_consumer_key: IVysXnVjx31A9b72xQwg
                            consumer_secret: j3XNNBdbk8YMBhHd9AHLCErTzlzobZmSV5wv1o922w

                    #культура.рф:
                    xn--80atdujec4e.xn--p1ai:
                        vkontakte:
                            app_id: 3119050
                            secret: niPCbh2ywoUeQOJSVPih
                        facebook:
                            app_id: 302490536525585
                            secret: 5c3ba92cecd1833c6773d085d58b0198

                    mk.dev.armd.ru:
                        twitter:
                            oauth_consumer_key: edBbssXZxodI6DNxd555w
                            consumer_secret: qtCdtWxiANPtyiTxpdnQ2PbNdMjtfq3aiKBx1hLHY

                    mk.armd.shams.su:
                        vkontakte:
                            app_id: 3119047
                            secret: d0H7euAEzj12bcxvcmMu
                        facebook:
                            app_id: 482442168446063
                            secret: 4dc17cf63e24d79b6b4a54360bc3db66
                        twitter:
                            oauth_consumer_key: F0lzOE5KpZQoR6lgF92g
                            consumer_secret: x426C9iJJvYOQhX7tK5VKEHfGxFyFFsX7bXkCbI53Tg



    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
