jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EXPERT, ROLE_SONATA_ADMIN, ROLE_MODERATOR, ROLE_CORRECTOR, ROLE_BLOGGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_EXPERT:      [ROLE_USER]
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_CORRECTOR:   [ROLE_USER]
        ROLE_BLOGGER:     [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # -> custom firewall for the admin area of the URL
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                login_path:             sonata_user_admin_security_login #/admin/login
                check_path:             sonata_user_admin_security_check #/admin/login_check
                default_target_path:    sonata_admin_dashboard #/admin/dashboard
                provider:               fos_userbundle
                use_forward:            false
                failure_path:           null
                use_referer:            true
            logout:
                path:           sonata_user_admin_security_logout #/admin/logout
                target:         sonata_user_admin_security_login #/admin/login

            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 360000
                domain:   ~ # Defaults to the current domain from $_SERVER
        # -> end custom configuration

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

#        oauth_authorize:
#            pattern:    ^/oauth/v2/auth
#            form_login:
#                provider:       fos_userbundle
#                login_path:     /login
#                use_forward:    true
#                check_path:     /login_check
#                default_target_path: armd_news_index_by_category
#                failure_path:   null
#                use_referer:    true
#                success_handler: armd_user.security.authentication_success_handler
#            logout:
#                path:           /logout
#                target:         armd_news_index_by_category
#                success_handler: armd_user.security.logout_success_handler
#            anonymous:          true

        oauth_api:
            pattern:    ^/oauth/api
            fos_oauth:  true
            stateless:  true

        oauth_atlas_api:
            pattern:    ^/atlas/api
            fos_oauth:  true
            stateless:  true

        # defaut login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            .*
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login #/login
                use_forward:    true
                check_path:     fos_user_security_check #/login_check
#                default_target_path: armd_news_index_by_category
                failure_path:   null
                use_referer:    true
                success_handler: armd_user.security.authentication_success_handler
            logout:
                path:           fos_user_security_logout #/logout
                target:         armd_news_index_by_category
                success_handler: armd_user.security.logout_success_handler
            anonymous:          true

            armd_social_auth:
                auth_provider_parameters:

                    # used by культура.рф
                    default:
                        vkontakte:
                            app_id: 3119050
                            secret: niPCbh2ywoUeQOJSVPih
                        facebook:
                            app_id: 302490536525585
                            secret: 5c3ba92cecd1833c6773d085d58b0198

                    culture.ru:
                        twitter:
                            oauth_consumer_key: oHZwTxIjcC8A6ScPhcUaMA
                            consumer_secret: YtWVcqQ4kU1yZ0FfyrG6V28w0XvWyIZDI9YQP4M
                        vkontakte:
                            app_id: 3702231
                            secret: fVGv4e7DWCBqAizsWlR4
                        facebook:
                            app_id: 549475125075147
                            secret: 89ac4602917e536d69d8fabdca55413e

                    mkmark.dev.armd.ru:
                        vkontakte:
                            app_id: 3702233
                            secret: LjQKUs7w8yuv9eyRSso2
                        facebook:
                            app_id: 213094462173030
                            secret: b676b6de6f0055fc63986335a1d83560



    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^(/(en|ru))?/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(en|ru))?/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(en|ru))?/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> custom access control for the admin area of the URL
        - { path: ^(/(en|ru))?/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(en|ru))?/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(en|ru))?/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        - { path: ^(/(en|ru))?/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(en|ru))?/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^(/(en|ru))?/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^(/(en|ru))?/oauth/api, roles: [ IS_AUTHENTICATED_FULLY ] }
