<?php

namespace Armd\AtlasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CultureObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureObjectRepository extends EntityRepository
{
    public function search($params=array())
    {
        $searchTerm = $params['term'];
        $categoryIds = $params['category'];
        $criteria = array(
            'title' => ''
        );
        return $this->findBy($criteria);
    }

}