<?php

namespace Armd\AtlasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
    public function filter($params=array())
    {
        $term = $params['term'];
        $categoryIds = $params['category'];

        $qb = $this->createQueryBuilder('o')
                   ->innerJoin('o.categories', 'c')
                   ->where('c IN (:categoryIds)')
                   ->setParameter('categoryIds', $categoryIds);

        $rows = $qb->getQuery()->getResult();
        return $rows;
    }

}