services:
    armd_user.activity_listener:
        class: Armd\UserBundle\Listener\ActivityListener
        arguments: [@security.context, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    armd_user.listener.post_auth_redirect:
        class: Armd\UserBundle\Listener\PostAuthRedirectListener
        arguments: [@security.context, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    armd_user.security.authentication_success_handler:
        class: Armd\UserBundle\Security\AuthenticationSuccessHandler
        arguments: [@security.http_utils, {}]        
        calls:
            - [setContainer, [@service_container]]
            
    armd_user.security.logout_success_handler:
        class: Armd\UserBundle\Security\LogoutSuccessHandler
        arguments: [@security.http_utils]
        calls:
            - [setContainer, [@service_container]]        

    fos_user.user_manager.default:
        class: Armd\UserBundle\Entity\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]
    
    armd_user.registration.form.type:
        class: Armd\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: armd_user_registration }

    armd_user.profile.form.type:
        class: Armd\UserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: armd_user_profile }

    armd_user.manager.acl:
        class: Armd\UserBundle\Security\AclManager
        arguments: [@security.acl.provider]
