<?php

namespace Armd\ChronicleBundle\Repository;

use Armd\ListBundle\Repository\BaseRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentRepository extends BaseRepository
{   
    function setCentury($century)
    {
        $this->qb
            ->andWhere("{$this->alias}.century = :century")
            ->setParameter('century', $century)
        ;
        
        return $this;
    }
    
    function orderByCentury($order = 'DESC')
    {
        $this->qb->orderBy("{$this->alias}.century", $order);
            
        return $this;
    }
    
    function orderByDate($order = 'ASC')
    {
        $this->qb->orderBy("{$this->alias}.date", $order);
            
        return $this;
    }
    
    function setPeriod(\DateTime $from, \DateTime $to)
    {
        $this->qb
            ->andWhere("{$this->alias}.date >= :from")
            ->andWhere("{$this->alias}.date < :to")
            ->setParameter('from', $from)
            ->setParameter('to', $to)
        ;
        
        return $this;
    }
}
