<?php

namespace Armd\ChronicleBundle\Repository;

use Armd\ListBundle\Repository\BaseRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends BaseRepository
{
    function selectDistinctCenturies()
    {
        $this->qb
            ->select("{$this->alias}.century")
            ->distinct()
        ;
        
        return $this;
    }
    
    function setCentury($century)
    {
        $this->qb
            ->andWhere("{$this->alias}.century = :century")
            ->setParameter('century', $century)
        ;
        
        return $this;
    }
    
    function orderByCentury($order = 'DESC')
    {
        $this->qb->orderBy("{$this->alias}.century", $order);
            
        return $this;
    }
    
    function orderByYear($order = 'DESC')
    {
        $this->qb->orderBy("{$this->alias}.year", $order);
            
        return $this;
    }    
}
