<?php

namespace Armd\ChronicleBundle\Repository;

use Armd\ListBundle\Repository\ListRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends ListRepository
{
    function selectDistinctYears()
    {
        $this->qb
            ->select("{$this->alias}.year")
            ->distinct();
        
        return $this;
    }
    
    function orderByYear($order = 'DESC')
    {
        $this->qb->orderBy("{$this->alias}.year", $order);
            
        return $this;
    }
}