services:
    armd_util.listener.locale_database_switcher:
        class: Armd\UtilBundle\EventListener\LocaleDatabaseSwitchListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 12 }

