services:
    fos_comment.acl.comment.security:
        class: Armd\CommentBundle\Acl\SecurityCommentAcl
        public: false
        arguments: [@security.context, @security.acl.object_identity_retrieval_strategy, @security.acl.provider, %fos_comment.model.comment.class%]

    fos_comment.acl.vote.security:
        class: Armd\CommentBundle\Acl\SecurityVoteAcl
        public: false
        arguments: [@security.context, @security.acl.object_identity_retrieval_strategy, @security.acl.provider, %fos_comment.model.vote.class%]
