<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130208115533 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE armd_museum ADD atlas_object_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE armd_museum ADD CONSTRAINT FK_F7F41989129049C2 FOREIGN KEY (atlas_object_id) REFERENCES atlas_object (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_F7F41989129049C2 ON armd_museum (atlas_object_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE armd_museum DROP atlas_object_id");
        $this->addSql("ALTER TABLE armd_museum DROP CONSTRAINT FK_F7F41989129049C2");
        $this->addSql("DROP INDEX IDX_F7F41989129049C2");
    }
}
