<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121205090741 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news ADD news_date TIMESTAMP(0) WITHOUT TIME ZONE NULL");
        $this->addSql("ALTER TABLE content_news ADD publish_from_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ADD publish_to_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ALTER date_from DROP NOT NULL");

        $this->addSql("UPDATE content_news SET news_date = date_from");

        $this->addSql("ALTER TABLE content_news ALTER news_date SET NOT NULL");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news DROP news_date");
        $this->addSql("ALTER TABLE content_news DROP publish_from_date");
        $this->addSql("ALTER TABLE content_news DROP publish_to_date");
        $this->addSql("ALTER TABLE content_news ALTER date_from SET NOT NULL");
    }
}
