<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130125142829 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("DELETE FROM tagging WHERE resource_type = 'armd_tag_global'");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
