<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120910082750 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE content_news SET published = 'f' WHERE published IS NULL");
        $this->addSql("ALTER TABLE content_news ALTER published SET NOT NULL");
        $this->addSql("ALTER TABLE content_news ADD published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("UPDATE content_news SET published_at = date_from WHERE category_id in (SELECT id FROM content_news_category WHERE filtrable = 't')");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
