<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120919174044 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE armd_comment_vote DROP CONSTRAINT fk_6722cff4f8697d13");
        $this->addSql("ALTER TABLE armd_cp_proposals DROP CONSTRAINT fk_ca9331fc1f55203d");
        $this->addSql("ALTER TABLE armd_comment_vote_object DROP CONSTRAINT fk_3ce14d1ae2904019");
        $this->addSql("ALTER TABLE armd_cp_proposals DROP CONSTRAINT fk_ca9331fcbd6be194");
        $this->addSql("ALTER TABLE armd_comment_comment DROP CONSTRAINT fk_ab261caee2904019");
        $this->addSql("ALTER TABLE content_news DROP CONSTRAINT fk_d0b17495e2904019");
        $this->addSql("ALTER TABLE armd_cp_proposals DROP CONSTRAINT fk_ca9331fce2904019");
        $this->addSql("DROP SEQUENCE armd_comment_comment_id_seq");
        $this->addSql("DROP SEQUENCE armd_comment_thread_id_seq");
        $this->addSql("DROP SEQUENCE armd_comment_vote_id_seq");
        $this->addSql("DROP SEQUENCE armd_comment_vote_object_id_seq");
        $this->addSql("DROP SEQUENCE armd_comment_vote_object_thread_id_seq");
        $this->addSql("DROP SEQUENCE armd_cp_proposals_id_seq");
        $this->addSql("DROP SEQUENCE armd_cp_topic_id_seq");
        $this->addSql("CREATE SEQUENCE comment_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE comment (id INT NOT NULL, thread_id VARCHAR(255) DEFAULT NULL, body TEXT NOT NULL, ancestors VARCHAR(1024) NOT NULL, depth INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_9474526CE2904019 ON comment (thread_id)");
        $this->addSql("CREATE TABLE comment_thread (id VARCHAR(255) NOT NULL, permalink VARCHAR(255) NOT NULL, is_commentable BOOLEAN NOT NULL, num_comments INT NOT NULL, last_comment_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526CE2904019 FOREIGN KEY (thread_id) REFERENCES comment_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("DROP TABLE armd_comment_vote_object");
        $this->addSql("DROP TABLE armd_comment_vote");
        $this->addSql("DROP TABLE armd_comment_comment");
        $this->addSql("DROP TABLE armd_cp_topic");
        $this->addSql("DROP TABLE armd_comment_vote_object_thread");
        $this->addSql("DROP TABLE armd_cp_proposals");
        $this->addSql("DROP TABLE armd_comment_thread");
        $this->addSql("ALTER TABLE media__media ALTER provider_metadata TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER facebook_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER twitter_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER gplus_data TYPE TEXT");
        $this->addSql("ALTER TABLE content_news ALTER thread_id TYPE VARCHAR(255)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news DROP CONSTRAINT FK_D0B17495E2904019");
        $this->addSql("ALTER TABLE comment DROP CONSTRAINT FK_9474526CE2904019");
        $this->addSql("DROP SEQUENCE comment_id_seq");
        $this->addSql("CREATE SEQUENCE acl_classes_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_object_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_security_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_comment_comment_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_comment_thread_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_comment_vote_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_comment_vote_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_comment_vote_object_thread_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_cp_proposals_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE armd_cp_topic_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE armd_comment_vote_object (id INT NOT NULL, thread_id INT DEFAULT NULL, voter_id INT DEFAULT NULL, value INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_3ce14d1aebb4b8ad ON armd_comment_vote_object (voter_id)");
        $this->addSql("CREATE UNIQUE INDEX voter_object ON armd_comment_vote_object (voter_id, thread_id, value)");
        $this->addSql("CREATE INDEX idx_3ce14d1ae2904019 ON armd_comment_vote_object (thread_id)");
        $this->addSql("CREATE TABLE armd_comment_vote (id INT NOT NULL, voter_id INT DEFAULT NULL, comment_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, value INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_6722cff4f8697d13 ON armd_comment_vote (comment_id)");
        $this->addSql("CREATE UNIQUE INDEX voter_comment ON armd_comment_vote (voter_id, comment_id, value)");
        $this->addSql("CREATE INDEX idx_6722cff4ebb4b8ad ON armd_comment_vote (voter_id)");
        $this->addSql("CREATE TABLE armd_comment_comment (id INT NOT NULL, thread_id INT DEFAULT NULL, author_id INT DEFAULT NULL, body TEXT NOT NULL, ancestors VARCHAR(1024) NOT NULL, depth INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state INT NOT NULL, score INT NOT NULL, countvotes INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_ab261caef675f31b ON armd_comment_comment (author_id)");
        $this->addSql("CREATE INDEX idx_ab261caee2904019 ON armd_comment_comment (thread_id)");
        $this->addSql("CREATE TABLE armd_cp_topic (id INT NOT NULL, title VARCHAR(100) NOT NULL, decription TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE armd_comment_vote_object_thread (id INT NOT NULL, isvoteable BOOLEAN NOT NULL, score INT NOT NULL, countvotes INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE armd_cp_proposals (id INT NOT NULL, topic_id INT DEFAULT NULL, voteobjectthread_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, content TEXT NOT NULL, enabled BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX idx_ca9331fce2904019 ON armd_cp_proposals (thread_id)");
        $this->addSql("CREATE INDEX idx_ca9331fcf675f31b ON armd_cp_proposals (author_id)");
        $this->addSql("CREATE INDEX idx_ca9331fc1f55203d ON armd_cp_proposals (topic_id)");
        $this->addSql("CREATE INDEX idx_ca9331fcbd6be194 ON armd_cp_proposals (voteobjectthread_id)");
        $this->addSql("CREATE TABLE armd_comment_thread (id INT NOT NULL, permalink VARCHAR(255) NOT NULL, is_commentable BOOLEAN NOT NULL, num_comments INT NOT NULL, last_comment_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE armd_comment_vote_object ADD CONSTRAINT fk_3ce14d1ae2904019 FOREIGN KEY (thread_id) REFERENCES armd_comment_vote_object_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_comment_vote_object ADD CONSTRAINT fk_3ce14d1aebb4b8ad FOREIGN KEY (voter_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_comment_vote ADD CONSTRAINT fk_6722cff4ebb4b8ad FOREIGN KEY (voter_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_comment_vote ADD CONSTRAINT fk_6722cff4f8697d13 FOREIGN KEY (comment_id) REFERENCES armd_comment_comment (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_comment_comment ADD CONSTRAINT fk_ab261caee2904019 FOREIGN KEY (thread_id) REFERENCES armd_comment_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_comment_comment ADD CONSTRAINT fk_ab261caef675f31b FOREIGN KEY (author_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_cp_proposals ADD CONSTRAINT fk_ca9331fc1f55203d FOREIGN KEY (topic_id) REFERENCES armd_cp_topic (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_cp_proposals ADD CONSTRAINT fk_ca9331fcbd6be194 FOREIGN KEY (voteobjectthread_id) REFERENCES armd_comment_vote_object_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_cp_proposals ADD CONSTRAINT fk_ca9331fce2904019 FOREIGN KEY (thread_id) REFERENCES armd_comment_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE armd_cp_proposals ADD CONSTRAINT fk_ca9331fcf675f31b FOREIGN KEY (author_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("DROP TABLE comment");
        $this->addSql("DROP TABLE comment_thread");
        $this->addSql("ALTER TABLE content_news ALTER thread_id TYPE INT");
        $this->addSql("ALTER TABLE fos_user_user ALTER facebook_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER twitter_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER gplus_data TYPE TEXT");
        $this->addSql("ALTER TABLE media__media ALTER provider_metadata TYPE TEXT");
    }
}
