<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121101200432 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news ADD is_on_map BOOLEAN DEFAULT 'false' NOT NULL");
        $this->addSql("ALTER TABLE content_news ADD lat NUMERIC(15, 10) DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ADD lon NUMERIC(15, 10) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news DROP is_on_map");
        $this->addSql("ALTER TABLE content_news DROP lat");
        $this->addSql("ALTER TABLE content_news DROP lon");
    }
}
