<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130211103755 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE lecture_super_type SET name = '100 фильмов для школьников' WHERE code = 'LECTURE_SUPER_TYPE_TOP100'");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
