<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120814145029 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // skip if data is already in DB
        $stmt = $this->connection->query('SELECT COUNT(*) count FROM lecture_category');
        $row = $stmt->fetch();
        $this->skipIf($row['count'] > 0, 'lecture_category is not empty');

        // add data
        $this->addSql('
            INSERT INTO lecture_category (title, root, lvl, lft, rgt)
            VALUES(:title, :root, :lvl, :lft, :rgt)
        ', array(
            'title' => '=== Корневая категория ===',
            'root' => 1,
            'lvl' => 0,
            'lft' => 0,
            'rgt' => 0

        ));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
