<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226144734 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object ADD side_banner_image_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE atlas_object ADD CONSTRAINT FK_E837B3021FA569BD FOREIGN KEY (side_banner_image_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_E837B3021FA569BD ON atlas_object (side_banner_image_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object DROP side_banner_image_id");
        $this->addSql("ALTER TABLE atlas_object DROP CONSTRAINT FK_E837B3021FA569BD");
        $this->addSql("DROP INDEX IDX_E837B3021FA569BD");
    }
}
