<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120821142034 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        if(!$schema->getTable('fos_user_user')->hasColumn('middlename')) {
            $this->addSql("ALTER TABLE fos_user_user ADD middlename VARCHAR(255) DEFAULT NULL");
        }
        if(!$schema->getTable('fos_user_user')->hasColumn('city')) {
            $this->addSql("ALTER TABLE fos_user_user ADD city VARCHAR(255) DEFAULT NULL");
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
