<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * This migration fixes cinema root category
 *
 */
class Version20121019184602 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $sql = 'UPDATE lecture_category
            SET
                lft = 1,
                rgt = 2,
                super_type_id = 3
            WHERE
                root = 3
                AND parent_id IS NULL
                AND super_type_id IS NULL
        ';
        $this->addSql($sql);

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
