<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120911134259 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE SEQUENCE armd_event_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE armd_event (id INT NOT NULL, region_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, date_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, city VARCHAR(255) NOT NULL, place VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE armd_event ADD published BOOLEAN NOT NULL");
        $this->addSql("ALTER TABLE armd_event ALTER city DROP NOT NULL");
        $this->addSql("CREATE INDEX IDX_37B9766F98260155 ON armd_event (region_id)");
        $this->addSql("ALTER TABLE armd_event ADD CONSTRAINT FK_37B9766F98260155 FOREIGN KEY (region_id) REFERENCES atlas_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
