<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827141743 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

        if($schema->hasSequence('content_tvigle_id_seq')) {
            $this->addSql("DROP SEQUENCE content_tvigle_id_seq");
        }
        if($schema->hasSequence('tvigle_task_id_seq')) {
            $this->addSql("DROP SEQUENCE tvigle_task_id_seq");
        }
        if($schema->hasTable('content_tvigle')) {
            $this->addSql("DROP TABLE content_tvigle");
        }
        if($schema->hasTable('tvigle_task')) {
            $this->addSql("DROP TABLE tvigle_task");
        }
        $this->addSql("ALTER TABLE media__media ALTER provider_metadata TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER facebook_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER twitter_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER gplus_data TYPE TEXT");
        if(!$schema->getTable('tvigle_video')->hasColumn('frame')) {
            $this->addSql("ALTER TABLE tvigle_video ADD frame TEXT DEFAULT NULL");

        }
        $this->addSql("ALTER TABLE banner ALTER open_in_new_window DROP NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE content_tvigle (id INT NOT NULL, tvigleid INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, duration INT DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, code TEXT DEFAULT NULL, status INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE tvigle_task (id INT NOT NULL, url VARCHAR(255) NOT NULL, videoid INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE banner ALTER open_in_new_window SET NOT NULL");
        $this->addSql("ALTER TABLE tvigle_video DROP frame");
        $this->addSql("ALTER TABLE fos_user_user ALTER facebook_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER twitter_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER gplus_data TYPE TEXT");
        $this->addSql("ALTER TABLE media__media ALTER provider_metadata TYPE TEXT");
    }
}
