<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130207182935 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE armd_museum_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE armd_museum_category (id INT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE armd_museum ADD region_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE armd_museum ADD CONSTRAINT FK_F7F4198998260155 FOREIGN KEY (region_id) REFERENCES atlas_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_F7F4198998260155 ON armd_museum (region_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE armd_museum_category_id_seq");
        $this->addSql("DROP TABLE armd_museum_category");
        $this->addSql("ALTER TABLE armd_museum DROP region_id");
    }
}
