<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827002302 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $stmt = $this->connection->query("
            SELECT id
            FROM lecture_super_type
            WHERE code = 'LECTURE_SUPER_TYPE_LECTURE'
        ");
        $row = $stmt->fetch();
        $lectureSuperTypeId = $row['id'];

        $this->addSql("
            UPDATE lecture
            SET lecture_super_type_id = :lecture_super_type_id
            WHERE lecture_super_type_id IS NULL
            ",
            array(
                'lecture_super_type_id' => $lectureSuperTypeId
            )
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
