<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121031153232 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news ADD video_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ADD CONSTRAINT FK_D0B1749529C1004E FOREIGN KEY (video_id) REFERENCES tvigle_video (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_D0B1749529C1004E ON content_news (video_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE content_news DROP video_id");
        $this->addSql("ALTER TABLE content_news DROP CONSTRAINT FK_D0B1749529C1004E");
        $this->addSql("DROP INDEX IDX_D0B1749529C1004E");
    }
}
