<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121120134630 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE lecture ADD seo_title VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE lecture ADD seo_description TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE lecture ADD seo_keywords TEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE lecture DROP seo_title");
        $this->addSql("ALTER TABLE lecture DROP seo_description");
        $this->addSql("ALTER TABLE lecture DROP seo_keywords");
    }
}
