<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121009132722 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE oauth_access_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE oauth_auth_code_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE oauth_client_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE oauth_refresh_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("ALTER TABLE fos_user_user ALTER facebook_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER twitter_data TYPE TEXT");
        $this->addSql("ALTER TABLE fos_user_user ALTER gplus_data TYPE TEXT");
        $this->addSql("ALTER TABLE oauth_access_token ADD token VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE oauth_access_token ADD expires_at INT DEFAULT NULL");
        $this->addSql("ALTER TABLE oauth_access_token ADD scope VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE oauth_auth_code ADD token VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE oauth_auth_code ADD redirect_uri TEXT NOT NULL");
        $this->addSql("ALTER TABLE oauth_auth_code ADD expires_at INT DEFAULT NULL");
        $this->addSql("ALTER TABLE oauth_auth_code ADD scope VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE oauth_client ADD random_id VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE oauth_client ADD redirect_uris TEXT NOT NULL");
        $this->addSql("ALTER TABLE oauth_client ADD secret VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE oauth_client ADD allowed_grant_types TEXT NOT NULL");
        $this->addSql("COMMENT ON COLUMN oauth_client.redirect_uris IS '(DC2Type:array)'");
        $this->addSql("COMMENT ON COLUMN oauth_client.allowed_grant_types IS '(DC2Type:array)'");
        $this->addSql("ALTER TABLE oauth_refresh_token ADD token VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE oauth_refresh_token ADD expires_at INT DEFAULT NULL");
        $this->addSql("ALTER TABLE oauth_refresh_token ADD scope VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE oauth_access_token_id_seq");
        $this->addSql("DROP SEQUENCE oauth_auth_code_id_seq");
        $this->addSql("DROP SEQUENCE oauth_client_id_seq");
        $this->addSql("DROP SEQUENCE oauth_refresh_token_id_seq");
        $this->addSql("ALTER TABLE oauth_access_token DROP token");
        $this->addSql("ALTER TABLE oauth_access_token DROP expires_at");
        $this->addSql("ALTER TABLE oauth_access_token DROP scope");
        $this->addSql("ALTER TABLE oauth_auth_code DROP token");
        $this->addSql("ALTER TABLE oauth_auth_code DROP redirect_uri");
        $this->addSql("ALTER TABLE oauth_auth_code DROP expires_at");
        $this->addSql("ALTER TABLE oauth_auth_code DROP scope");
        $this->addSql("ALTER TABLE oauth_client DROP random_id");
        $this->addSql("ALTER TABLE oauth_client DROP redirect_uris");
        $this->addSql("ALTER TABLE oauth_client DROP secret");
        $this->addSql("ALTER TABLE oauth_client DROP allowed_grant_types");
        $this->addSql("ALTER TABLE oauth_refresh_token DROP token");
        $this->addSql("ALTER TABLE oauth_refresh_token DROP expires_at");
        $this->addSql("ALTER TABLE oauth_refresh_token DROP scope");
    }
}
