<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121119184326 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object ALTER seo_description TYPE TEXT");
        $this->addSql("ALTER TABLE atlas_object ALTER seo_keywords TYPE TEXT");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object ALTER seo_description TYPE VARCHAR(255)");
        $this->addSql("ALTER TABLE atlas_object ALTER seo_keywords TYPE VARCHAR(255)");
    }
}
