<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130206184510 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE content_news_theme_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE content_news_theme (id INT NOT NULL, icon_media_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_74F3D6A4F78AF24A ON content_news_theme (icon_media_id)");
        $this->addSql("ALTER TABLE content_news_theme ADD CONSTRAINT FK_74F3D6A4F78AF24A FOREIGN KEY (icon_media_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE content_news ADD theme_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ADD CONSTRAINT FK_D0B1749559027487 FOREIGN KEY (theme_id) REFERENCES content_news_theme (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_D0B1749559027487 ON content_news (theme_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP INDEX IDX_D0B1749559027487");
        $this->addSql("ALTER TABLE content_news DROP CONSTRAINT FK_D0B1749559027487");
        $this->addSql("DROP SEQUENCE content_news_theme_id_seq");
        $this->addSql("DROP TABLE content_news_theme");
        $this->addSql("ALTER TABLE content_news DROP theme_id");
    }
}
