<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121022132049 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("INSERT INTO atlas_object_status (id, title, action_title) VALUES (0, 'не нужна', 'Send to moderation queue')");
        $this->addSql("INSERT INTO atlas_object_status (id, title, action_title) VALUES (1, 'ожидает модерации', 'Object is waiting for moderation')");
        $this->addSql("INSERT INTO atlas_object_status (id, title, action_title) VALUES (2, 'одобрено', 'Object was added to the map')");
        $this->addSql("INSERT INTO atlas_object_status (id, title, action_title) VALUES (3, 'отклонено', 'Object is rejected!')");
        $this->addSql("UPDATE atlas_object SET status = 0");
        // this up() migration is autogenerated, please modify it to your needs

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
