<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121031193953 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE atlas_object_virtual_tour (object_id INT NOT NULL, museum_id INT NOT NULL, PRIMARY KEY(object_id, museum_id))");
        $this->addSql("CREATE INDEX IDX_9F4AABBD232D562B ON atlas_object_virtual_tour (object_id)");
        $this->addSql("CREATE INDEX IDX_9F4AABBD4B52E5B5 ON atlas_object_virtual_tour (museum_id)");
        $this->addSql("ALTER TABLE atlas_object_virtual_tour ADD CONSTRAINT FK_9F4AABBD232D562B FOREIGN KEY (object_id) REFERENCES atlas_object (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE atlas_object_virtual_tour ADD CONSTRAINT FK_9F4AABBD4B52E5B5 FOREIGN KEY (museum_id) REFERENCES armd_museum (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP TABLE atlas_object_virtual_tour");
    }
}
