<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120814144141 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("
            ALTER TABLE atlas_category
            ALTER COLUMN id SET DEFAULT nextval('atlas_category_id_seq'::regclass)");

        $this->addSql("
            ALTER TABLE lecture_category
            ALTER COLUMN id SET DEFAULT nextval('lecture_category_id_seq'::regclass)");

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
