<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120829180107 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // select primary categories
        $conn = $this->connection;
        $sql = "SELECT id, primary_atlas_category_id FROM atlas_object WHERE primary_atlas_category_id IS NOT NULL";
        $stmt = $conn->query($sql);
        while($row = $stmt->fetch()) {
            // select secondary categories
            $sql = "SELECT COUNT(*) count
                FROM atlas_category_object
                WHERE category_id = :category_id
                    AND object_id = :object_id
            ";
            $stmtCount = $conn->prepare($sql);
            $stmtCount->execute(array(
                'category_id' => $row['primary_atlas_category_id'],
                'object_id' => $row['id']
            ));
            $rowCount = $stmtCount->fetch();

            // add primary category as secondary if needed
            if((int) $rowCount['count'] === 0) {
                $this->addSql("
                    INSERT INTO atlas_category_object (object_id, category_id)
                    VALUES (:object_id, :category_id)
                ", array(
                    'object_id' => $row['id'],
                    'category_id' => $row['primary_atlas_category_id']
                ));
            }
        }

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
