<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226190610 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE lecture_person_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE lecture_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE lecture_role_person_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE lecture_person (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE lecture_role (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE lecture_role_person (id INT NOT NULL, lecture_id INT DEFAULT NULL, role_id INT DEFAULT NULL, person_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_EEC0274335E32FCD ON lecture_role_person (lecture_id)");
        $this->addSql("CREATE INDEX IDX_EEC02743D60322AC ON lecture_role_person (role_id)");
        $this->addSql("CREATE INDEX IDX_EEC02743217BBB47 ON lecture_role_person (person_id)");
        $this->addSql("ALTER TABLE lecture_role_person ADD CONSTRAINT FK_EEC0274335E32FCD FOREIGN KEY (lecture_id) REFERENCES lecture (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE lecture_role_person ADD CONSTRAINT FK_EEC02743D60322AC FOREIGN KEY (role_id) REFERENCES lecture_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE lecture_role_person ADD CONSTRAINT FK_EEC02743217BBB47 FOREIGN KEY (person_id) REFERENCES lecture_person (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE lecture_role_person DROP CONSTRAINT FK_EEC02743217BBB47");
        $this->addSql("ALTER TABLE lecture_role_person DROP CONSTRAINT FK_EEC02743D60322AC");
        $this->addSql("DROP SEQUENCE lecture_person_id_seq");
        $this->addSql("DROP SEQUENCE lecture_role_id_seq");
        $this->addSql("DROP SEQUENCE lecture_role_person_id_seq");
        $this->addSql("DROP TABLE lecture_person");
        $this->addSql("DROP TABLE lecture_role");
        $this->addSql("DROP TABLE lecture_role_person");
    }
}
