<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121229134141 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE armd_museum ADD banner_image_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE armd_museum ADD CONSTRAINT FK_F7F419893F9CEB4E FOREIGN KEY (banner_image_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_F7F419893F9CEB4E ON armd_museum (banner_image_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE armd_museum DROP banner_image_id");
        $this->addSql("ALTER TABLE armd_museum DROP CONSTRAINT FK_F7F419893F9CEB4E");
        $this->addSql("DROP INDEX IDX_F7F419893F9CEB4E");
    }
}
