<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120928073728 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE content_news_subject_id_seq RENAME TO armd_main_subject_id_seq");
        $this->addSql("ALTER TABLE content_news_subject RENAME TO armd_main_subject");
        
        $this->addSql("ALTER TABLE armd_event RENAME COLUMN category_id TO subject_id");
        $this->addSql("ALTER TABLE armd_event DROP CONSTRAINT fk_37b9766f12469de2");        
        $this->addSql("DROP INDEX idx_37b9766f12469de2");

        $this->addSql("UPDATE armd_event SET subject_id = s.s_id FROM (
            SELECT
            	s.id AS s_id,
            	c.id AS c_id
            FROM
            	armd_event_category c,
            	armd_main_subject s
            WHERE
            	c.slug = s.slug
        ) as s
        WHERE subject_id = s.c_id");
        
        $this->addSql("ALTER TABLE armd_event ADD CONSTRAINT FK_37B9766F23EDC87 FOREIGN KEY (subject_id) REFERENCES armd_main_subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_37B9766F23EDC87 ON armd_event (subject_id)");
        $this->addSql("DROP TABLE armd_event_category");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
