<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121004151224 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE oauth_access_token (id INT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_F7FA86A419EB6921 ON oauth_access_token (client_id)");
        $this->addSql("CREATE INDEX IDX_F7FA86A4A76ED395 ON oauth_access_token (user_id)");
        $this->addSql("CREATE TABLE oauth_auth_code (id INT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_4D12F0E019EB6921 ON oauth_auth_code (client_id)");
        $this->addSql("CREATE INDEX IDX_4D12F0E0A76ED395 ON oauth_auth_code (user_id)");
        $this->addSql("CREATE TABLE oauth_client (id INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE oauth_refresh_token (id INT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_55DCF75519EB6921 ON oauth_refresh_token (client_id)");
        $this->addSql("CREATE INDEX IDX_55DCF755A76ED395 ON oauth_refresh_token (user_id)");
        $this->addSql("ALTER TABLE oauth_access_token ADD CONSTRAINT FK_F7FA86A419EB6921 FOREIGN KEY (client_id) REFERENCES oauth_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE oauth_access_token ADD CONSTRAINT FK_F7FA86A4A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE oauth_auth_code ADD CONSTRAINT FK_4D12F0E019EB6921 FOREIGN KEY (client_id) REFERENCES oauth_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE oauth_auth_code ADD CONSTRAINT FK_4D12F0E0A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE oauth_refresh_token ADD CONSTRAINT FK_55DCF75519EB6921 FOREIGN KEY (client_id) REFERENCES oauth_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE oauth_refresh_token ADD CONSTRAINT FK_55DCF755A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE oauth_access_token DROP CONSTRAINT FK_F7FA86A419EB6921");
        $this->addSql("ALTER TABLE oauth_auth_code DROP CONSTRAINT FK_4D12F0E019EB6921");
        $this->addSql("ALTER TABLE oauth_refresh_token DROP CONSTRAINT FK_55DCF75519EB6921");
        $this->addSql("DROP SEQUENCE oauth_access_token_id_seq");
        $this->addSql("DROP SEQUENCE oauth_auth_code_id_seq");
        $this->addSql("DROP SEQUENCE oauth_client_id_seq");
        $this->addSql("DROP SEQUENCE oauth_refresh_token_id_seq");
        $this->addSql("CREATE TABLE armd_event_category (id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("DROP TABLE oauth_access_token");
        $this->addSql("DROP TABLE oauth_auth_code");
        $this->addSql("DROP TABLE oauth_client");
        $this->addSql("DROP TABLE oauth_refresh_token");
    }
}
