<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121207161802 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

        $this->addSql("UPDATE atlas_object SET created_at = '2012-07-01' WHERE created_at IS NULL");
        $this->addSql("UPDATE atlas_object SET updated_at = '2012-07-01' WHERE updated_at IS NULL");
        $this->addSql("ALTER TABLE atlas_object ALTER created_at SET NOT NULL");
        $this->addSql("ALTER TABLE atlas_object ALTER updated_at SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object ALTER created_at DROP NOT NULL");
        $this->addSql("ALTER TABLE atlas_object ALTER updated_at DROP NOT NULL");
    }
}
