<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120731215319 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("update media__media set context = 'news' where id in (select image_id from content_news)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
