<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120927161655 extends AbstractMigration
{
    private $subjects = array(
        array(
            'title' => 'Бородино',
            'slug'  => 'borodino',
        ),
        array(
            'title' => '1150 лет российской государственности',
            'slug'  => '1150'
        ),
    );
    public function up(Schema $schema)
    {
        $this->addSql("CREATE SEQUENCE content_news_subject_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE content_news_subject (id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        
        foreach ($this->subjects as $s) {
            $this->addSql("INSERT INTO content_news_subject (id, title, slug) VALUES (nextval('content_news_subject_id_seq'), :title, :slug)", $s);    
        }
        
        $this->addSql("ALTER TABLE content_news ADD subject_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE content_news ADD CONSTRAINT FK_D0B1749523EDC87 FOREIGN KEY (subject_id) REFERENCES content_news_subject (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_D0B1749523EDC87 ON content_news (subject_id)");
        
        $this->addSql("UPDATE content_news SET subject_id = (SELECT id FROM content_news_subject WHERE slug = 'borodino') WHERE borodino = 't'");
        $this->addSql("ALTER TABLE content_news DROP borodino");
        $this->addSql("ALTER TABLE content_news ALTER category_id SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
