<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120824215441 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // skip if data is already in DB
        $stmt = $this->connection->query('SELECT COUNT(*) count FROM atlas_region');
        $row = $stmt->fetch();
        $this->skipIf($row['count'] > 0, 'atlas_region is not empty');

        foreach($this->getRegions() as $region) {
            $this->addSql("
                INSERT INTO atlas_region (id, title, sort_index)
                VALUES(nextval('lecture_type_id_seq'::regclass), :title, :sort_index)
            ", array(
                'title' => $region['title'],
                'sort_index' => $region['sort_index'],
            ));
        }

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }


    protected function getRegions()
    {
        $regions = array(
            array('title' => "Москва", 'sort_index' => 500),
            array('title' => "Тюменская область", 'sort_index' => 500),
            array('title' => "Ханты-Мансийский автономный округ", 'sort_index' => 500),
            array('title' => "Московская область", 'sort_index' => 500),
            array('title' => "Санкт-Петербург", 'sort_index' => 500),
            array('title' => "KrasnoyarskKray-Красноярский край", 'sort_index' => 500),
            array('title' => "Свердловская область", 'sort_index' => 500),
            array('title' => "Краснодарский край", 'sort_index' => 500),
            array('title' => "Татарстан", 'sort_index' => 500),
            array('title' => "Ямало-Ненецкий автономный округ", 'sort_index' => 500),
            array('title' => "Башкортостан", 'sort_index' => 500),
            array('title' => "Самарская область", 'sort_index' => 500),
            array('title' => "Нижегородская область", 'sort_index' => 500),
            array('title' => "Челябинская область", 'sort_index' => 500),
            array('title' => "Ростовская область", 'sort_index' => 500),
            array('title' => "Пермский край", 'sort_index' => 500),
            array('title' => "Кемеровская область", 'sort_index' => 500),
            array('title' => "Иркутская область", 'sort_index' => 500),
            array('title' => "Ленинградская область", 'sort_index' => 500),
            array('title' => "Сахалинская область", 'sort_index' => 500),
            array('title' => "Новосибирская область", 'sort_index' => 500),
            array('title' => "Приморский край", 'sort_index' => 500),
            array('title' => "Оренбургская область", 'sort_index' => 500),
            array('title' => "Волгоградская область", 'sort_index' => 500),
            array('title' => "Белгородская область", 'sort_index' => 500),
            array('title' => "Республика Саха", 'sort_index' => 500),
            array('title' => "Омская область", 'sort_index' => 500),
            array('title' => "Саратовская область", 'sort_index' => 500),
            array('title' => "Архангельская область,", 'sort_index' => 500),
            array('title' => "(включая НАО)", 'sort_index' => 500),
            array('title' => "Республика Коми", 'sort_index' => 500),
            array('title' => "Хабаровский край", 'sort_index' => 500),
            array('title' => "Воронежская область", 'sort_index' => 500),
            array('title' => "Ставропольский край", 'sort_index' => 500),
            array('title' => "Алтайский край", 'sort_index' => 500),
            array('title' => "Дагестан", 'sort_index' => 500),
            array('title' => "TomskOblastТомская область", 'sort_index' => 500),
            array('title' => "Удмуртия", 'sort_index' => 500),
            array('title' => "Липецкая область", 'sort_index' => 500),
            array('title' => "Вологодская область", 'sort_index' => 500),
            array('title' => "Тульская область", 'sort_index' => 500),
            array('title' => "Мурманская область", 'sort_index' => 500),
            array('title' => "Ярославская область", 'sort_index' => 500),
            array('title' => "Владимирская область", 'sort_index' => 500),
            array('title' => "Тверская область", 'sort_index' => 500),
            array('title' => "Калининградская область", 'sort_index' => 500),
            array('title' => "Курская область", 'sort_index' => 500),
            array('title' => "Калужская область", 'sort_index' => 500),
            array('title' => "Амурская область", 'sort_index' => 500),
            array('title' => "Ульяновская область", 'sort_index' => 500),
            array('title' => "Рязанская область", 'sort_index' => 500),
            array('title' => "Кировская область", 'sort_index' => 500),
            array('title' => "Забайкальский край", 'sort_index' => 500),
            array('title' => "Пензенская область", 'sort_index' => 500),
            array('title' => "Чувашия", 'sort_index' => 500),
            array('title' => "Тамбовская область", 'sort_index' => 500),
            array('title' => "Ненецкий автономный округ", 'sort_index' => 500),
            array('title' => "Астраханская область", 'sort_index' => 500),
            array('title' => "Брянская область", 'sort_index' => 500),
            array('title' => "Смоленская область", 'sort_index' => 500),
            array('title' => "Бурятия", 'sort_index' => 500),
            array('title' => "Карелия", 'sort_index' => 500),
            array('title' => "Новгородская область", 'sort_index' => 500),
            array('title' => "Курганская область", 'sort_index' => 500),
            array('title' => "Мордовия", 'sort_index' => 500),
            array('title' => "Орловская область", 'sort_index' => 500),
            array('title' => "Ивановская область", 'sort_index' => 500),
            array('title' => "Камчатский край", 'sort_index' => 500),
            array('title' => "Хакасия", 'sort_index' => 500),
            array('title' => "Костромская область", 'sort_index' => 500),
            array('title' => "Псковская область", 'sort_index' => 500),
            array('title' => "Марий Эл", 'sort_index' => 500),
            array('title' => "Кабардино-Балкария", 'sort_index' => 500),
            array('title' => "Северная Осетия", 'sort_index' => 500),
            array('title' => "Чечня", 'sort_index' => 500),
            array('title' => "Магаданская область", 'sort_index' => 500),
            array('title' => "Адыгея", 'sort_index' => 500),
            array('title' => "Карачаево-Черкесия", 'sort_index' => 500),
            array('title' => "Чукотский автономный округ", 'sort_index' => 500),
            array('title' => "Еврейская автономная область", 'sort_index' => 500),
            array('title' => "Тыва", 'sort_index' => 500),
            array('title' => "Калмыкия", 'sort_index' => 500),
            array('title' => "Республика Алтай", 'sort_index' => 500),
            array('title' => "Ингушетия", 'sort_index' => 500),
        );

        return $regions;
    }
}
