<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120924075723 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("CREATE SEQUENCE armd_event_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE armd_event_category (id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE armd_event ADD category_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE armd_event ADD CONSTRAINT FK_37B9766F12469DE2 FOREIGN KEY (category_id) REFERENCES armd_event_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_37B9766F12469DE2 ON armd_event (category_id)");
        
        $this->addSql("INSERT INTO armd_event_category (id, title, slug) VALUES (nextval('armd_event_category_id_seq'), :title, :slug)", array('title' => 'Бородино', 'slug' => 'borodino'));
        $this->addSql("UPDATE armd_event SET category_id = (SELECT id FROM armd_event_category WHERE slug = :slug)", array('slug' => 'borodino'));
        
        $this->addSql("ALTER TABLE armd_event ALTER category_id SET NOT NULL");
        
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
