<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120815194825 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        if ($schema->getTable('content_chronicle_accident')->hasColumn('year')) {
            $this->addSql("update content_chronicle_accident set date = to_date(year || '.01.01', 'YYYY.MM.DD')");
        }
        $this->addSql("ALTER TABLE content_chronicle_accident ALTER date SET NOT NULL");

        if ($schema->getTable('content_chronicle_accident')->hasColumn('year')) {
            $this->addSql("ALTER TABLE content_chronicle_accident DROP year");
        }

        if (!$schema->getTable('content_chronicle_accident')->hasColumn('century')) {
            $this->addSql("ALTER TABLE content_chronicle_accident ADD century INT DEFAULT NULL");
        }

        $this->addSql("update content_chronicle_accident set century = floor(date_part('year', date) / 100) + 1");
        $this->addSql("ALTER TABLE content_chronicle_accident ALTER century SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
