<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121010162901 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $sql = "
            INSERT INTO oauth_client (
                id,
                random_id,
                redirect_uris,
                secret,
                allowed_grant_types
            ) VALUES(
                :id,
                :random_id,
                :redirect_uris,
                :secret,
                :allowed_grant_types
            )
        ";

        $this->addSql(
            $sql,
            array(
                'id' => 1,
                'random_id' => 'people-roskult',
                'redirect_uris' => 'a:0:{}',
                'secret' => substr(md5(mt_rand() . time()), 0, 20),
                'allowed_grant_types' => 'a:1:{i:0;s:8:"password";}'
            )
        );

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
