<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120814193114 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // skip if data is already in DB
        $stmt = $this->connection->query('SELECT COUNT(*) count FROM lecture_type');
        $row = $stmt->fetch();
        $this->skipIf($row['count'] > 0, 'lecture_type is not empty');

        // add data
        $types = array(
            'LECTURE_TYPE_VIDEO' => 'Видео',
            'LECTURE_TYPE_AUDIO' => 'Аудио',
            'LECTURE_TYPE_TEXT' => 'Текст',
        );
        foreach ($types as $key => $val) {
            $this->addSql("
                INSERT INTO lecture_type (id, name, code)
                VALUES(nextval('lecture_type_id_seq'::regclass), :name, :code)
                ",
                array(
                    'name' => $val,
                    'code' => $key
                )
            );
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
