<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120830133136 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        if(!$schema->getTable('atlas_object')->hasColumn('published')) {
            $this->addSql("ALTER TABLE atlas_object ADD published BOOLEAN NULL");
        }
        $this->addSql("UPDATE atlas_object SET published = false");
        $this->addSql("
            UPDATE atlas_object SET published = true
            WHERE lon <> 0 AND lon IS NOT NULL
             AND lat <> 0 AND lon IS NOT NULL
        ");
        $this->addSql("ALTER TABLE atlas_object ALTER published SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_object DROP published");
    }
}
