<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121228110137 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_category ADD slug VARCHAR(255) DEFAULT NULL");
        $this->addSql("UPDATE atlas_category SET slug = 'type'  WHERE title = 'Тип объекта'");
        $this->addSql("UPDATE atlas_category SET slug = 'thematic'  WHERE title = 'Тематика'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atlas_category DROP slug");
    }
}
