<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121113120238 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE lecture ADD media_lecture_video_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE lecture ADD media_trailer_video_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE lecture ADD CONSTRAINT FK_C1677948F5809C5 FOREIGN KEY (media_lecture_video_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE lecture ADD CONSTRAINT FK_C16779488444A6FC FOREIGN KEY (media_trailer_video_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_C1677948F5809C5 ON lecture (media_lecture_video_id)");
        $this->addSql("CREATE INDEX IDX_C16779488444A6FC ON lecture (media_trailer_video_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE lecture DROP media_lecture_video_id");
        $this->addSql("ALTER TABLE lecture DROP media_trailer_video_id");
        $this->addSql("ALTER TABLE lecture DROP CONSTRAINT FK_C1677948F5809C5");
        $this->addSql("ALTER TABLE lecture DROP CONSTRAINT FK_C16779488444A6FC");
        $this->addSql("DROP INDEX IDX_C1677948F5809C5");
        $this->addSql("DROP INDEX IDX_C16779488444A6FC");
    }
}
