<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120821142034 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("ALTER TABLE fos_user_user ADD middlename VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user_user ADD city VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user_user ADD sex BOOLEAN DEFAULT NULL");
        $this->addSql("update fos_user_user set sex = 't'");
        $this->addSql("ALTER TABLE fos_user_user ALTER sex SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
