<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827131748 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $table = $schema->getTable('tvigle_video');
        if(!$table->hasColumn('frame')) {
            $this->addSql("
                ALTER TABLE tvigle_video ADD frame TEXT DEFAULT NULL
                "
            );
        }


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
