<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130125120734 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("UPDATE tagging SET resource_type = 'armd_news' WHERE resource_id::int > 1941");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
