<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120803154113 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs

        $sql = array();
        //$sql[] = 'ALTER TABLE content_news ADD thread_id INT DEFAULT NULL';
        //$sql[] = 'ALTER TABLE content_news ADD CONSTRAINT FK_D0B17495E2904019 FOREIGN KEY (thread_id) REFERENCES armd_comment_thread (id) NOT DEFERRABLE INITIALLY IMMEDIATE';
        //$sql[] = 'CREATE INDEX IDX_D0B17495E2904019 ON content_news (thread_id)';

        $sql[] = 'alter table  armd_comment_thread add news_id integer default null';

        $sql[] = "
insert into armd_comment_thread
select nextval('armd_comment_thread_id_seq'),
'/',
't',
0,
null,
id from content_news where thread_id is null;
";

        $sql[] = "alter table  acl_object_identities add isnew integer default null";

        $sql[] = "
insert into acl_object_identities
select nextval('acl_object_identities_id_seq'),
null,
3,
id,
't',
1 from armd_comment_thread where news_id is not null
";

        $sql[] = "
insert into acl_object_identity_ancestors
select id, id
from acl_object_identities where isnew is not null
";
        $sql[] = "alter table  acl_object_identities drop isnew";




        $sql[] = "
update content_news
set thread_id = armd_comment_thread.id
from armd_comment_thread
where armd_comment_thread.news_id = content_news.id
        ";

        $sql[] = "
alter table  armd_comment_thread drop news_id
        ";

        $sql[] = '
ALTER TABLE content_news ALTER COLUMN thread_id SET NOT NULL
        ';


        foreach($sql as $line) {
            $this->addSql($line);
        }


    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
