<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120827012639 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // skip if data is already in DB
        $stmt = $this->connection->query('SELECT COUNT(*) count FROM lecture_super_type');
        $row = $stmt->fetch();

        $this->skipIf($row['count'] > 0, 'lecture_super_type is already filled');

        // add data
        $types = array(
            'LECTURE_SUPER_TYPE_LECTURE' => 'Лекция',
            'LECTURE_SUPER_TYPE_VIDEO_TRANSLATION' => 'Трансляция',
        );
        foreach ($types as $key => $val) {
            $this->addSql("
                INSERT INTO lecture_super_type (id, name, code)
                VALUES(nextval('lecture_super_type_id_seq'::regclass), :name, :code)
                ",
                array(
                    'name' => $val,
                    'code' => $key
                )
            );
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
