<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130125143332 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql("DELETE FROM tag t WHERE t.name = ''");
        $this->addSql("
            DELETE FROM tagging tn WHERE
            tn.tag_id IN (
                SELECT t.id
                FROM tag t
                WHERE t.name = '' OR t.name IS NULL
            )
        ");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs

    }
}
