parameters:
    armd_culture_map.controller.culture_map.class: Armd\CultureMapBundle\Controller\CultureMapController

services:
    armd_culture_map.controller.culture_map:
        class: %armd_culture_map.controller.culture_map.class%
        calls:
            - [ setContainer, [ @service_container ] ]

