#_sys_culturemap_regions:
#    pattern:  /regions
#    defaults: { _controller: ArmdCultureMapBundle:CultureMap:regions }

_sys_culturemap_region:
    pattern:  /region
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:region }

_sys_culturemap_markers:
    pattern:  /markers
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:markers }

_sys_culturemap_object:
    pattern:  /object
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:object }

_sys_culturemap_subject:
    pattern:  /subject
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:subject }
