_sys_culturemap_regions:
    pattern:  /ru/sys/map/regions
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:regions }

_sys_culturemap_region:
    pattern:  /ru/sys/map/region
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:region }

_sys_culturemap_markers:
    pattern:  /ru/sys/map/markers
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:markers }