_sys_culturemap_regions:
    pattern:  /ru/sys/map/regions
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:regions }

_sys_culturemap_region:
    pattern:  /ru/sys/map/region
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:region }

_sys_culturemap_markers:
    pattern:  /ru/sys/map/markers
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:markers }

_sys_culturemap_object:
    pattern:  /ru/sys/map/object
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:object }

_sys_culturemap_subject:
    pattern:  /ru/sys/map/subject
    defaults: { _controller: ArmdCultureMapBundle:CultureMap:subject }
