parameters:
    armd_culture_map.usagetypes:
        types:
            list:
                controller: CultureMap
                action: list
            atlas:
                controller: CultureMap
                action: atlas
            subject:
                controller: CultureMap
                action: subject
                route:
                    pattern: /{id}
                    requirements:
                        id: \d+
        group:
            atlas:
                types: [atlas]
            list:
                types: [list, subject]
            subject:
                types: [subject]

services:
    armd_culture_map.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_map", %armd_culture_map.usagetypes%, "ArmdCultureMapBundle"]
        tags:
            -  { name: armd_cms.usage }
