parameters:
    armd_culture_map.usagetypes:
        types:
            list:
                controller: culturemap
                action: list
                title: Карта субъектов РФ
            subject:
                controller: culturemap
                action: subject
                title: Карточка субъекта РФ
                route:
                    pattern: /{id}
                    requirements:
                        id: \d+
        group:
            list:
                types: [list]
            subject:
                types: [subject]

services:
    armd_culture_map.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_culture_map", %armd_culture_map.usagetypes%, "ArmdCultureMapBundle"]
        tags:
            -  { name: armd_cms.usage }
