<?php

namespace Armd\AtlasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristClusterRepository extends EntityRepository
{

    public function getDataForFilter($ids=array())
    {
        $qb = $this->createQueryBuilder('t1')
            ->select('t1.id, t1.title, 0 as hasIcon')
            ;
/*
        if ($ids) {
            $qb->andWhere('t2.id IN (:ids)')
               ->setParameter('ids', $ids);
        }
*/
        $rows = $qb->getQuery()->getResult();
        $result = array(
                  array("id" => 0,
                        "title" => "Туристические кластеры",
                        "tags" => $rows
                  ));
/*
        $tags = array();
        $cats = array();
        $result = array();
        foreach ($rows as $row) {
            $cats[$row['id']] = $row['category'];
            $tags[$row['id']][] = array(
                'id' => $row['tag_id'],
                'title' => $row['tag'],
                'hasIcon' => ($row[0]->getIconMedia() ? true : false),
            );
        }
        foreach ($cats as $categoryId => $categoryTitle) {
            $result[] = array(
                'id' => $categoryId,
                'title' => $categoryTitle,
                'tags' => $tags[$categoryId],
            );
        }
 */
        return $result;
    }

}
