<?php

namespace Armd\EventBundle\Repository;

use Armd\Bundle\NewsBundle\Repository\NewsRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends NewsRepository
{
    public function findByDatePeriod($beginDate='', $endDate='', $page=1)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select(array('e', 's', 'i'))
            ->from('ArmdEventBundle:Event', 'e')
            ->innerJoin('e.schedule', 's')
            ->leftJoin('e.image', 'i')
            ->where('s.beginDate BETWEEN ?1 AND ?2')
            ->orWhere('s.endDate BETWEEN ?1 AND ?2')
            ->andWhere('e.showInCollage=true')
            ->setParameters(array(
                1 => $beginDate,
                2 => $endDate.' 23:59:59',
            ))
            ->getQuery();
        $result = $query->getResult();
        return $result;
    }
}