<?php

namespace Armd\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findByDatePeriod(\DatePeriod $period)
    {
/*
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select(array('e', 'p'))
            ->from('ArmdEventBundle:Shedule', 's')
            ->innerJoin('s.event', 'e')
            ->innerJoin('s.place', 'p')
            ->orderBy('s.date', 'DESC')
        ->getQuery();
            
        return $query->getResult();                        
*/
    }
}