services:
    armd_mk_comment.sonata_admin.comment:
        class: Armd\MkCommentBundle\Admin\CommentAdmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Comment
                label: Comments
                show_in_dashboard: true
                label_translator_strategy: sonata.admin.label.strategy.underscore
        arguments: [null, Armd\MkCommentBundle\Entity\Comment, ArmdMkCommentBundle:CRUD]
