services:
    armd_tourist_route.sonata_admin.category:
        class: Armd\TouristRouteBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tourist routes, label: Tourist route categories, show_in_dashboard: true }
        arguments: [null, Armd\TouristRouteBundle\Entity\Category, SonataAdminBundle:CRUD, @service_container]

    armd_tourist_route.sonata_admin.point:
        class: Armd\TouristRouteBundle\Admin\PointAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tourist routes, label: Tourist route points, show_in_dashboard: true }
        arguments: [null, Armd\TouristRouteBundle\Entity\Point, SonataAdminBundle:CRUD, @service_container]

    armd_tourist_route.sonata_admin.route:
        class: Armd\TouristRouteBundle\Admin\RouteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tourist routes, label: Tourist routes, show_in_dashboard: true }
        arguments: [null, Armd\TouristRouteBundle\Entity\Route, ArmdTouristRouteBundle:RouteCrud, @service_container]
