parameters:
    armd_news.manager.news.entity:  Armd\NewsBundle\Entity\News
    armd_news.manager.news.class:   Armd\NewsBundle\Entity\NewsManager

services:
    armd_news.entity_manager:
        alias: doctrine.orm.default_entity_manager

    armd_news.admin.category:
        class: Armd\NewsBundle\Admin\Category
        tags:
            - { name: sonata.admin, manager_type: orm, group: News, label: Categories }
        arguments: [null, Armd\NewsBundle\Entity\Category, SonataAdminBundle:CRUD, @service_container]
        
    armd_news.admin.news:
        class: Armd\NewsBundle\Admin\News
        tags:
            - { name: sonata.admin, manager_type: orm, group: News, label: News }
        arguments: [null, %armd_news.manager.news.entity%, SonataAdminBundle:CRUD, @service_container]
        
    armd_news.manager.news:
        class: %armd_news.manager.news.class%
        arguments: [@armd_event.entity_manager, %armd_news.manager.news.entity%, @service_container]
        
    armd_news.controller.news:
        class: Armd\NewsBundle\Controller\NewsController
        arguments:
            container: "@service_container"

    armd_news.listener.news:
        class: Armd\NewsBundle\EventListener\NewsListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: onFlush }
