services:
    armd.content.news.admin.category:
        class: Armd\NewsBundle\Admin\Category
        tags:
            - { name: sonata.admin, manager_type: orm, group: News, label: Categories }
        arguments: [null, Armd\NewsBundle\Entity\Category, SonataAdminBundle:CRUD, @service_container]
        
    armd.content.news.admin.news:
        class: Armd\NewsBundle\Admin\News
        tags:
            - { name: sonata.admin, manager_type: orm, group: News, label: News }
            - { name: armd.content.admin }
        arguments: [null, Armd\NewsBundle\Entity\News, SonataAdminBundle:CRUD, @service_container]
        
    armd_news.controller.news:
        class: Armd\NewsBundle\Controller\NewsController
        arguments:
            container: "@service_container"        