services:
    armd_tag.form.type.tag:
        class: Armd\TagBundle\Form\Type\TagType
        arguments: [@doctrine.orm.entity_manager, @fpn_tag.tag_manager]
        tags:
            - { name: form.type, alias: armd_tag }

