services:
    damedia_special_project.sonata_admin.page:
        class: Damedia\SpecialProjectBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Страницы" }
        arguments:
            - null
            - Damedia\SpecialProjectBundle\Entity\Page
            - 'DamediaSpecialProjectBundle:PageCRUD'

    damedia_special_project.sonata_admin.template:
        class: Damedia\SpecialProjectBundle\Admin\TemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Шаблоны" }
        arguments:
            - null
            - Damedia\SpecialProjectBundle\Entity\Template
            - 'SonataAdminBundle:CRUD'

    damedia_special_project.sonata_admin.block:
            class: Damedia\SpecialProjectBundle\Admin\BlockAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Блоки" }
            arguments:
                - null
                - Damedia\SpecialProjectBundle\Entity\Block
                - 'SonataAdminBundle:CRUD'

    damedia_special_project.sonata_admin.chunk:
                class: Damedia\SpecialProjectBundle\Admin\ChunkAdmin
                tags:
                    - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Куски" }
                arguments:
                    - null
                    - Damedia\SpecialProjectBundle\Entity\Chunk
                    - 'SonataAdminBundle:CRUD'