services:
    damedia_special_project.sonata_admin.page:
        class: Damedia\SpecialProjectBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Страницы" }
        arguments:
            - null
            - Damedia\SpecialProjectBundle\Entity\Page
            - 'DamediaSpecialProjectBundle:PageAdmin'

    damedia_special_project.sonata_admin.template:
        class: Damedia\SpecialProjectBundle\Admin\TemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Спецпроекты, label: "Шаблоны" }
        arguments:
            - null
            - Damedia\SpecialProjectBundle\Entity\Template
            - 'SonataAdminBundle:CRUD'