damedia_foreign_entity:
    pattern:  admin/damedia/specialproject/page/snippet
    defaults: { _controller: DamediaSpecialProjectBundle:Render:snippet }

get_images_jsonlist:
    pattern:  admin/damedia/specialproject/imageslist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getImagesJson }
    
get_snippet_jsonlist:
    pattern:  admin/damedia/specialproject/page/getSnippetJsonlist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getSnippetJsonlist }

get_tiny_ac_form:
    pattern:  admin/damedia/specialproject/page/getTinyAcForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTinyAcForm }

get_tiny_gallery_form:
    pattern: admin/damedia/specialproject/page/getTinyGalleryForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTinyGalleryForm }

get_tiny_media_form:
    pattern:  admin/damedia/specialproject/page/getTinyMediaForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTinyMediaForm }
    
get_template_blocks_form:
    pattern:  admin/damedia/specialproject/page/getTemplateBlocksForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTemplateBlocksForm }
    requirements:
        _method:  POST

damedia_special_project_list:
    pattern:  project
    defaults: { _controller: DamediaSpecialProjectBundle:Render:index }

damedia_special_project_view:
    pattern:  project/{slug}
    defaults: { _controller: DamediaSpecialProjectBundle:Render:view }
