damedia_special_project_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DamediaSpecialProjectBundle:Default:index }

_admin_ajax:
    resource: "@SomethingAdminBundle/Controller/AjaxController.php"
    type:     annotation
    prefix:   /admin/ajax
