damedia_foreign_entity:
    pattern:  admin/damedia/specialproject/page/snippet/{entity}/{itemId}/{view}
    defaults: { _controller: DamediaSpecialProjectBundle:Render:snippet }

get_images_jsonlist:
    pattern:  admin/damedia/specialproject/imageslist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getImagesJson }
    
get_snippet_jsonlist:
    pattern:  admin/damedia/specialproject/page/getSnippetJsonlist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getSnippetJsonlist }

get_news_jsonlist:
    pattern:  admin/damedia/specialproject/page/getNewsJsonlist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getNewsJsonlist }

get_entity_viewslist:
    pattern:  admin/damedia/specialproject/page/getEntityViewslist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getEntityViewslist }

get_tiny_media_form:
    pattern:  admin/damedia/specialproject/page/getTinyMediaForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTinyMediaForm }
    
get_template_blocks_form:
    pattern:  admin/damedia/specialproject/page/getTemplateBlocksForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTemplateBlocksForm }
    requirements:
        _method:  POST

damedia_special_project_view:
    pattern:  project/{slug}
    defaults: { _controller: DamediaSpecialProjectBundle:Render:view }
