get_snippet_jsonlist:
    pattern:  admin/damedia/specialproject/page/getSnippetJsonlist
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getSnippetJsonlist }

get_tiny_ac_form:
    pattern:  admin/damedia/specialproject/page/getTinyAcForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTinyAcForm }

get_template_blocks_form:
    pattern:  admin/damedia/specialproject/page/getTemplateBlocksForm
    defaults: { _controller: DamediaSpecialProjectBundle:PageManagement:getTemplateBlocksForm }
    requirements:
      _method:  POST

damedia_special_project_view:
    pattern:  /project/{slug}
    defaults: { _controller: DamediaSpecialProjectBundle:Render:index }