ajax_get_template_blocks_form:
    pattern:  admin/damedia/specialproject/page/getTemplateBlocksForm
    defaults: { _controller: DamediaSpecialProjectBundle:AdminAjax:getTemplateBlocksForm }
    requirements:
      _method:  POST

#damedia_special_project_view:
#    pattern:  /project/{page}
#    defaults: { DamediaSpecialProjectBundle:Render:index, page: last }