parameters:
#    damedia_special_project.example.class: Damedia\SpecialProjectBundle\Example

services:
#    damedia_special_project.example:
#        class: %damedia_special_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
