parameters:
    special_project_helper.class:      Damedia\SpecialProjectBundle\Service\SpecialProjectHelper

services:
    special_project_helper:
        class:        "%special_project_helper.class%"