<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Datetime $last_activitylastActivity
     */
    private $lastActivity;

    /**
     * @var integer $okUid
     */
    protected $okUid;

    /**
     * @var integer $vkUid
     */
    protected $vkUid;

    /**
     * @var integer $fbUid
     */
    protected $fbUid;

    /**
     * @var integer $twUid
     */
    protected $twUid;

    /**
     * @var string $socialName
     */
    protected $socialName;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Get okUid
     *
     * @return integer $okUid
     */
    public function getOkUid()
    {
        return $this->okUid;
    }

    /**
     * Set okUid
     *
     * @param integer $okUid
     *
     * @return User
     */
    public function setOkUid($okUid)
    {
        $this->okUid = $okUid;

        return $this;
    }

    /**
     * Get vkUid
     *
     * @return integer $vkUid
     */
    public function getVkUid()
    {
        return $this->vkUid;
    }

    /**
     * Set vkUid
     *
     * @param integer $vkUid
     *
     * @return User
     */
    public function setVkUid($vkUid)
    {
        $this->vkUid = $vkUid;

        return $this;
    }

    /**
     * Get fbUid
     *
     * @return integer $fbUid
     */
    public function getFbUid()
    {
        return $this->fbUid;
    }

    /**
     * Set fbUid
     *
     * @param integer $fbUid
     *
     * @return User
     */
    public function setFbUid($fbUid)
    {
        $this->fbUid = $fbUid;

        return $this;
    }

    /**
     * Get twUid
     *
     * @return integer $twUid
     */
    public function getTwUid()
    {
        return $this->twUid;
    }

    /**
     * Set twUid
     *
     * @param integer $twUid
     *
     * @return User
     */
    public function setTwUid($twUid)
    {
        $this->twUid = $twUid;

        return $this;
    }

    /**
     * Set lastActivity
     *
     * @param \Datetime $lastActivity
     * @return User
     */
    public function setLastActivity($lastActivity)
    {
        $this->lastActivity = $lastActivity;
        return $this;
    }

    /**
     * Get lastActivity
     *
     * @return \Datetime
     */
    public function getLastActivity()
    {
        return $this->lastActivity;
    }

    /**
     * Set socialName
     *
     * @param string $socialName
     * @return User
     */
    public function setSocialName($socialName)
    {
        $this->socialName = $socialName;
        return $this;
    }

    /**
     * Get socialName
     *
     * @return \Datetime
     */
    public function getSocialName()
    {
        return $this->socialName;
    }
}
