parameters:

services:
    armd_region.admin.region:
        class: Armd\RegionBundle\Admin\RegionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Regions }
        arguments: [null, Armd\RegionBundle\Entity\Region, SonataAdminBundle:CRUD]