services:
    armd.cp.topic.admin:
        class: Armd\CommunicationPlatformBundle\Admin\TopicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Topic }
            - { name: armd.content.admin }
        arguments: [null, Armd\CommunicationPlatformBundle\Entity\Topic, SonataAdminBundle:CRUD]

    armd.cp.proposals.admin:
        class: Armd\CommunicationPlatformBundle\Admin\ProposalsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Proposals }
            - { name: armd.content.admin }
        arguments: [null, Armd\CommunicationPlatformBundle\Entity\Proposals, SonataAdminBundle:CRUD]