services:
    armd_museum.admin.museum:
        class: Armd\MuseumBundle\Admin\Museum
        tags:
            - { name: sonata.admin, manager_type: orm, group: Museums, label: Museums }
        arguments: [null, Armd\MuseumBundle\Entity\Museum, SonataAdminBundle:CRUD, @service_container]

    armd_museum.manager.museum:
        class: Armd\MuseumBundle\Entity\MuseumManager
        arguments: [@doctrine.orm.default_entity_manager, @knp_paginator, @search.sphinxsearch.search]
