parameters:

services:
    armd_event.admin.event:
        class: Armd\EventBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Events }
            - { name: armd.content.admin }            
        arguments: [null, Armd\EventBundle\Entity\Event, SonataAdminBundle:CRUD, @service_container]
        
    armd_event.admin.schedule:
        class: Armd\EventBundle\Admin\ScheduleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Events Schedule}
            - { name: armd.content.admin }            
        arguments: [null, Armd\EventBundle\Entity\Schedule, SonataAdminBundle:CRUD, @service_container]        