parameters:

services:
    armd_event.admin.event:
        class: Armd\EventBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Events }
        arguments: [null, Armd\EventBundle\Entity\Event, SonataAdminBundle:CRUD, @service_container]
        
    armd_event.admin.shedule:
        class: Armd\EventBundle\Admin\SheduleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Events Shedule}
        arguments: [null, Armd\EventBundle\Entity\Shedule, SonataAdminBundle:CRUD, @service_container]        