parameters:
    armd_event.controller.event.class:      Armd\EventBundle\Controller\EventController
    armd_event.controller.schedule.class:    Armd\EventBundle\Controller\ScheduleController    

services:
    armd_event.controller.event:
        class: %armd_event.controller.event.class%
        calls:
            - [ setContainer, [ @service_container ] ]
            
    armd_event.controller.schedule:
        class: %armd_event.controller.schedule.class%
        calls:
            - [ setContainer, [ @service_container ] ]
            