parameters:
    armd_event.manager.category.entity: Armd\EventBundle\Entity\Category
    armd_event.manager.event.entity:    Armd\EventBundle\Entity\Event
    armd_event.manager.event.class:     Armd\EventBundle\Entity\EventManager

services:
    armd_event.entity_manager:
        alias: doctrine.orm.default_entity_manager

    armd_event.admin.event:
        class: Armd\EventBundle\Admin\Event
        tags:
            - { name: sonata.admin, manager_type: orm, group: Events, label: Events }
        arguments: [null, %armd_event.manager.event.entity%, SonataAdminBundle:CRUD, @service_container]

    armd_event.manager.event:
        class: %armd_event.manager.event.class%
        arguments: [@armd_event.entity_manager, %armd_event.manager.event.entity%]
