parameters:
    armd_event.usagetypes:
        types:
            item:
                controller: Event
                action: item                
                route:
                    pattern: /item-{id}
                    requirements:
                        id: \d+
            list:
                controller: Event
                action: list
                route:
                    pattern: /{page}
                    defaults:
                        page: 1
                    requirements:
                        page: \d+
                params:
                    per_page:
                        title: Количество элементов на странице
                        type: int                        
                        default: 10
                        requirements: 1
        group:
            list:
                types: [list]
            listitem:
                types: [item, list]

services:
    armd_event.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_event", %armd_event.usagetypes%, "ArmdEventBundle"]
        tags:
            -  { name: armd_cms.usage }