parameters:
    armd_event.usagetypes:
        types:
            item:
                controller: Event
                action: item                
                route:
                    pattern: /item-{id}
                    requirements:
                        id: \d+
            list:
                controller: Event
                action: list
                route:
                    pattern: /{page}
                    defaults:
                        page: 1
                    requirements:
                        page: \d+
                params:
                    content_stream:
                        title: Информационный поток
                        type: entity
                        entity: ArmdContentAbstractBundle:Stream
                        addField: id
                        viewField: Name
                        default: 0

                    per_page:
                        title: Количество элементов на странице
                        type: int                        
                        default: 10
                        requirements: 1
            archive:
                controller: Event
                action: archive
                route:
                    pattern: /{from}/{to}/{page}
                    defaults:
                        from: null
                        to:   null
                        page: 1
                    requirements:
                        from: \d{4}-\d{2}-\d{2}
                        to:   \d{4}-\d{2}-\d{2}                        
                        page: \d+
                params:
                    per_page:
                        title: Количество элементов на странице
                        type: int                        
                        default: 10
                        requirements: 1
                
        group:
            list:
                types: [list]
            listitem:
                types: [item, list]
            archive:
                types: [archive]

services:
    armd_event.usagetype:
        class: %armd_cms.usagetype.class%
        arguments: ["armd_event", %armd_event.usagetypes%, "ArmdEventBundle"]
        tags:
            -  { name: armd_cms.usage }