armd_online_translation:
    pattern:  /
    defaults: { _controller: ArmdOnlineTranslationBundle:Default:index }
    
armd_online_translation_set_notification:
    pattern:  /set-notification
    defaults: { _controller: ArmdOnlineTranslationBundle:Default:setNotification }
