parameters:
#    armd_online_translation.example.class: Armd\OnlineTranslationBundle\Example

services:
#    armd_online_translation.example:
#        class: %armd_online_translation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
