armd_user_token_login:
    pattern: /login-token/{loginToken}
    defaults: { _controller: ArmdUserBundle:Authentication:authenticateByLoginToken}

armd_user_comments_list:
    pattern: /profile/comments/
    defaults: { _controller: ArmdUserBundle:Profile:listComments}

armd_user_comments_notice:
    pattern: /profile/notices/
    defaults: { _controller: ArmdUserBundle:Profile:listNotices}
