parameters:
#    blog.example.class: Armd\BlogBundle\Example

services:
    armd_press_center.admin.press_center:
        class: Armd\PressCenterBundle\Admin\PressCenterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: PressCenter, label: PressCenter }
        arguments: [null, Armd\PressCenterBundle\Entity\PressCenter, SonataAdminBundle:CRUD, @service_container]
