services:
    armd_atlas.sonata_admin.category:
        class: Armd\AtlasBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Atlas, label: Categories, show_in_dashboard: true }
        arguments: [null, Armd\AtlasBundle\Entity\Category, SonataAdminBundle:CRUD, @service_container]


    armd_atlas.sonata_admin.object:
        class: Armd\AtlasBundle\Admin\ObjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Atlas, label: Objects, show_in_dashboard: true }
        arguments: [null, Armd\AtlasBundle\Entity\Object, ArmdAtlasBundle:ObjectCrud, @service_container]

    armd_atlas.sonata_admin.region:
        class: Armd\AtlasBundle\Admin\RegionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directories, label: Regions, show_in_dashboard: true }
        arguments: [null, Armd\AtlasBundle\Entity\Region, SonataAdminBundle:CRUD]


    armd_atlas.sonata_admin.literature:
        class: Armd\AtlasBundle\Admin\LiteratureAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Atlas, label: Literature, show_in_dashboard: false }
        arguments: [null, Armd\AtlasBundle\Entity\Literature, SonataAdminBundle:CRUD, @service_container]

    armd_atlas.sonata_admin.object_hint:
        class: Armd\AtlasBundle\Admin\ObjectHintAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Atlas, label: ObjectHint, show_in_dashboard: false }
        arguments: [null, Armd\AtlasBundle\Entity\ObjectHint, SonataAdminBundle:CRUD, @service_container]

    armd_atlas.sonata_admin.object_custom:
        class: Armd\AtlasBundle\Admin\ObjectCustomAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Atlas, label: CustomObjects, show_in_dashboard: true }
        arguments: [null, Armd\AtlasBundle\Entity\Object, ArmdAtlasBundle:ObjectCustom, @service_container]
