services:

    armd.atlas_bundle.type.armd_object_categories:
            class: Armd\AtlasBundle\Form\Type\ObjectCategoriesType
            arguments: [@doctrine.orm.entity_manager]
            tags:
                - { name: form.type, alias: armd_atlas_object_categories }
