services:
    armd_atlas.listener.media:
        class: Armd\AtlasBundle\EventListener\MediaListener
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    armd_atlas.listener.category:
        class: Armd\AtlasBundle\EventListener\CategoryListener
        tags:
            - { name: doctrine.event_listener, event: preRemove }
