<?php
namespace Armd\PaperArchiveBundle\Manager;

use Doctrine\ORM\EntityManager;
use Armd\PaperArchiveBundle\Entity\PaperArchive;
use Application\Sonata\MediaBundle\Entity\Media;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class PaperArchiveManager
{
    private $em;

    public function __construct(EntityManager $em, Container $container)
    {
        $this->em = $em;
        $this->container = $container;
    }

    public function createPreview(PaperArchive $entity){
        $image = $this->createImage($entity->getFile());
        $media = $this->createMedia($image, $entity->getTitle());
        $this->addMediaToEntity($media->getId(), $entity->getId());

        if (file_exists($this->getTempImagePath())) {
            unlink($this->getTempImagePath());
        }

        if (file_exists($this->getTempPdfPath())) {
            unlink($this->getTempPdfPath());
        }
    }

    public function createImage(Media $file)
    {
        $mediaPool = $this->container->get('sonata.media.pool');
        $provider = $mediaPool->getProvider($file->getProviderName());
        $filesystem = $provider->getFilesystem();

        $key = $provider->getReferenceImage($file);
        file_put_contents($this->getTempPdfPath(), $filesystem->read($key));

        $gm = new \Imagick();
        $gm->readImage($this->getTempPdfPath().'[0]');
        $gm->setImageFormat("jpg");
        $gm->setCompressionQuality(100);
        $tmpfile = $this->getTempImagePath();
        $gm->writeImage($tmpfile);
        return $tmpfile;
    }

    public function createMedia($image, $title)
    {
        $media = new Media();
        $mediaFile = new UploadedFile($image, $image);
        $media->setBinaryContent($mediaFile);
        $media->setContext('paper_archive');
        $media->setTitle($title);
        $media->setProviderName('sonata.media.provider.image');
        $mediaManager = $this->container->get('sonata.media.manager.media');
        $mediaManager->save($media);
        return $media;
    }

    public function addMediaToEntity($mediaId, $entityId)
    {
        return $this->em->createQuery('
                UPDATE ArmdPaperArchiveBundle:PaperArchive p
                SET p.image = :imageId
                WHERE p.id = :entityId'
            )->setParameters(array(
                'imageId' => $mediaId,
                'entityId' => $entityId
            ))->getResult();
    }

    protected function getTempPdfPath()
    {
        return sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'pdf_for_autogeneration.pdf';
    }

    protected function getTempImagePath()
    {
        return sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'AutogeneratedPreview.jpg';
    }

}