services:
  activity_listener:
    class: Application\Sonata\UserBundle\Listener\ActivityListener
    arguments: [@security.context, @doctrine]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

  fos_user.user_manager.default:
    class: Application\Sonata\UserBundle\Entity\UserManager
    arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]